"..\.venv\Lib\site-packages\PySide6\uic.exe" -g python about.ui -o ..\ui\ui_layout_about.py
"..\.venv\Lib\site-packages\PySide6\uic.exe" -g python cycleedit.ui -o ..\ui\ui_layout_cycle_edit.py
"..\.venv\Lib\site-packages\PySide6\uic.exe" -g python laser.ui -o ..\ui\ui_layout_laser.py
"..\.venv\Lib\site-packages\PySide6\uic.exe" -g python logviewer.ui -o ..\ui\ui_layout_log_viewer.py
"..\.venv\Lib\site-packages\PySide6\uic.exe" -g python main.ui -o ..\ui\ui_layout_main.py
"..\.venv\Lib\site-packages\PySide6\uic.exe" -g python ncccalc.ui -o ..\ui\ui_layout_ncc_calc.py
"..\.venv\Lib\site-packages\PySide6\uic.exe" -g python newbatch.ui -o ..\ui\ui_layout_new_batch.py
"..\.venv\Lib\site-packages\PySide6\uic.exe" -g python planchetbatch.ui -o ..\ui\ui_layout_planchet_batch.py
"..\.venv\Lib\site-packages\PySide6\uic.exe" -g python simplebatch.ui -o ..\ui\ui_layout_simple_batch.py
"..\.venv\Lib\site-packages\PySide6\uic.exe" -g python xymanualcontrol.ui -o ..\ui\ui_layout_xy_manual_control.py
"..\.venv\Lib\site-packages\PySide6\rcc.exe" -g python main.qrc -o ..\main_rc.py
