# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import main_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1800, 1000)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1800, 1000))
        MainWindow.setMaximumSize(QSize(1800, 1000))
        font = QFont()
        font.setFamily(u"Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u":/main/iconPyMSRun.svg", QSize(), QIcon.Normal, QIcon.Off)
        icon.addFile(u":/main/iconPyMSRun.svg", QSize(), QIcon.Disabled, QIcon.Off)
        icon.addFile(u":/main/iconPyMSRun.svg", QSize(), QIcon.Selected, QIcon.Off)
        icon.addFile(u":/main/iconPyMSRun.svg", QSize(), QIcon.Selected, QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"border-color: rgb(255, 255, 255);\n"
"font: 10pt \"Segoe UI\";\n"
"background-color: rgb(230, 230, 230);")
        MainWindow.setAnimated(True)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        font1 = QFont()
        font1.setFamily(u"Segoe UI")
        font1.setPointSize(10)
        self.actionExit.setFont(font1)
        self.actionStartNewBatch = QAction(MainWindow)
        self.actionStartNewBatch.setObjectName(u"actionStartNewBatch")
        self.actionStartNewBatch.setFont(font1)
        self.actionXYOpenStatusPage = QAction(MainWindow)
        self.actionXYOpenStatusPage.setObjectName(u"actionXYOpenStatusPage")
        self.actionXYOpenStatusPage.setFont(font1)
        self.actionXYOpenLogPage = QAction(MainWindow)
        self.actionXYOpenLogPage.setObjectName(u"actionXYOpenLogPage")
        self.actionXYOpenLogPage.setFont(font1)
        self.actionValveOpenStatusPage = QAction(MainWindow)
        self.actionValveOpenStatusPage.setObjectName(u"actionValveOpenStatusPage")
        self.actionValveOpenStatusPage.setFont(font1)
        self.actionValveOpenLogPage = QAction(MainWindow)
        self.actionValveOpenLogPage.setObjectName(u"actionValveOpenLogPage")
        self.actionValveOpenLogPage.setFont(font1)
        self.actionManualControl = QAction(MainWindow)
        self.actionManualControl.setObjectName(u"actionManualControl")
        self.actionManualControl.setFont(font1)
        self.actionViewPyMSLog = QAction(MainWindow)
        self.actionViewPyMSLog.setObjectName(u"actionViewPyMSLog")
        self.actionViewPyMSLog.setFont(font1)
        self.actionAboutPyMS = QAction(MainWindow)
        self.actionAboutPyMS.setObjectName(u"actionAboutPyMS")
        self.actionAboutPyMS.setFont(font1)
        self.actionViewPyMSSettings = QAction(MainWindow)
        self.actionViewPyMSSettings.setObjectName(u"actionViewPyMSSettings")
        self.actionViewPyMSSettings.setFont(font1)
        self.actionEdit_Cycle_Steps = QAction(MainWindow)
        self.actionEdit_Cycle_Steps.setObjectName(u"actionEdit_Cycle_Steps")
        self.actionEdit_Cycle_Steps.setFont(font1)
        self.actionPumpOpenStatusPage = QAction(MainWindow)
        self.actionPumpOpenStatusPage.setObjectName(u"actionPumpOpenStatusPage")
        self.actionPumpOpenLogPage = QAction(MainWindow)
        self.actionPumpOpenLogPage.setObjectName(u"actionPumpOpenLogPage")
        self.actionPyroLaserOn = QAction(MainWindow)
        self.actionPyroLaserOn.setObjectName(u"actionPyroLaserOn")
        self.actionPyroLaserOff = QAction(MainWindow)
        self.actionPyroLaserOff.setObjectName(u"actionPyroLaserOff")
        self.actionCO2LaserOn = QAction(MainWindow)
        self.actionCO2LaserOn.setObjectName(u"actionCO2LaserOn")
        self.actionCO2LaserOff = QAction(MainWindow)
        self.actionCO2LaserOff.setObjectName(u"actionCO2LaserOff")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frmHeLine = QFrame(self.centralwidget)
        self.frmHeLine.setObjectName(u"frmHeLine")
        self.frmHeLine.setEnabled(True)
        self.frmHeLine.setGeometry(QRect(330, 100, 950, 852))
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frmHeLine.sizePolicy().hasHeightForWidth())
        self.frmHeLine.setSizePolicy(sizePolicy1)
        self.frmHeLine.setMinimumSize(QSize(949, 852))
        self.frmHeLine.setMaximumSize(QSize(950, 852))
        self.frmHeLine.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.frmHeLine.setFrameShape(QFrame.Box)
        self.frmHeLine.setFrameShadow(QFrame.Plain)
        self.frmHeLine.setLineWidth(1)
        self.frmHeLine.setMidLineWidth(1)
        self.imgLaser = QFrame(self.frmHeLine)
        self.imgLaser.setObjectName(u"imgLaser")
        self.imgLaser.setEnabled(False)
        self.imgLaser.setGeometry(QRect(72, 361, 110, 116))
        self.imgLaser.setStyleSheet(u"image: url(:/main/laser.png);")
        self.imgLaser.setFrameShape(QFrame.NoFrame)
        self.imgLaser.setFrameShadow(QFrame.Plain)
        self.spinLaserPower = QDoubleSpinBox(self.frmHeLine)
        self.spinLaserPower.setObjectName(u"spinLaserPower")
        self.spinLaserPower.setGeometry(QRect(83, 560, 100, 30))
        self.spinLaserPower.setFont(font)
        self.spinLaserPower.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.spinLaserPower.setDecimals(0)
        self.spinLaserPower.setMinimum(0.000000000000000)
        self.spinLaserPower.setMaximum(99.000000000000000)
        self.spinLaserPower.setSingleStep(1.000000000000000)
        self.wValve1 = QWidget(self.frmHeLine)
        self.wValve1.setObjectName(u"wValve1")
        self.wValve1.setGeometry(QRect(269, 261, 35, 35))
        self.wValve1.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.tbValve1 = QPushButton(self.frmHeLine)
        self.tbValve1.setObjectName(u"tbValve1")
        self.tbValve1.setGeometry(QRect(271, 263, 36, 31))
        self.wValve2 = QWidget(self.frmHeLine)
        self.wValve2.setObjectName(u"wValve2")
        self.wValve2.setGeometry(QRect(337, 260, 36, 36))
        self.wValve2.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.tbValve2 = QPushButton(self.frmHeLine)
        self.tbValve2.setObjectName(u"tbValve2")
        self.tbValve2.setGeometry(QRect(338, 261, 36, 35))
        self.wValve6 = QWidget(self.frmHeLine)
        self.wValve6.setObjectName(u"wValve6")
        self.wValve6.setGeometry(QRect(336, 116, 36, 36))
        self.wValve6.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.wValve7 = QWidget(self.frmHeLine)
        self.wValve7.setObjectName(u"wValve7")
        self.wValve7.setGeometry(QRect(482, 116, 36, 36))
        self.wValve7.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.wValve3 = QWidget(self.frmHeLine)
        self.wValve3.setObjectName(u"wValve3")
        self.wValve3.setGeometry(QRect(482, 260, 36, 36))
        self.wValve3.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.wValve4 = QWidget(self.frmHeLine)
        self.wValve4.setObjectName(u"wValve4")
        self.wValve4.setGeometry(QRect(551, 260, 36, 36))
        self.wValve4.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.wValve10 = QWidget(self.frmHeLine)
        self.wValve10.setObjectName(u"wValve10")
        self.wValve10.setGeometry(QRect(336, 401, 36, 36))
        self.wValve10.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.wValve11 = QWidget(self.frmHeLine)
        self.wValve11.setObjectName(u"wValve11")
        self.wValve11.setGeometry(QRect(482, 401, 36, 36))
        self.wValve11.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.wValve12 = QWidget(self.frmHeLine)
        self.wValve12.setObjectName(u"wValve12")
        self.wValve12.setGeometry(QRect(315, 694, 36, 36))
        self.wValve12.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.wValve8 = QWidget(self.frmHeLine)
        self.wValve8.setObjectName(u"wValve8")
        self.wValve8.setGeometry(QRect(408, 188, 36, 36))
        self.wValve8.setStyleSheet(u"image: url(:/valves/valve green vertical.png);")
        self.wValve5 = QWidget(self.frmHeLine)
        self.wValve5.setObjectName(u"wValve5")
        self.wValve5.setGeometry(QRect(407, 521, 36, 36))
        self.wValve5.setStyleSheet(u"image: url(:/valves/valve green vertical.png);")
        self.wValve13 = QWidget(self.frmHeLine)
        self.wValve13.setObjectName(u"wValve13")
        self.wValve13.setGeometry(QRect(480, 522, 36, 36))
        self.wValve13.setStyleSheet(u"image: url(:/valves/valve green vertical.png);")
        self.tbValve6 = QPushButton(self.frmHeLine)
        self.tbValve6.setObjectName(u"tbValve6")
        self.tbValve6.setGeometry(QRect(338, 115, 36, 36))
        self.tbValve7 = QPushButton(self.frmHeLine)
        self.tbValve7.setObjectName(u"tbValve7")
        self.tbValve7.setGeometry(QRect(484, 116, 36, 36))
        self.tbValve8 = QPushButton(self.frmHeLine)
        self.tbValve8.setObjectName(u"tbValve8")
        self.tbValve8.setGeometry(QRect(409, 189, 36, 36))
        self.tbValve3 = QPushButton(self.frmHeLine)
        self.tbValve3.setObjectName(u"tbValve3")
        self.tbValve3.setGeometry(QRect(485, 260, 36, 36))
        self.tbValve4 = QPushButton(self.frmHeLine)
        self.tbValve4.setObjectName(u"tbValve4")
        self.tbValve4.setGeometry(QRect(554, 262, 36, 36))
        self.tbValve10 = QPushButton(self.frmHeLine)
        self.tbValve10.setObjectName(u"tbValve10")
        self.tbValve10.setGeometry(QRect(339, 401, 36, 36))
        self.tbValve11 = QPushButton(self.frmHeLine)
        self.tbValve11.setObjectName(u"tbValve11")
        self.tbValve11.setGeometry(QRect(484, 400, 36, 36))
        self.tbValve5 = QPushButton(self.frmHeLine)
        self.tbValve5.setObjectName(u"tbValve5")
        self.tbValve5.setGeometry(QRect(408, 518, 36, 36))
        self.tbValve13 = QPushButton(self.frmHeLine)
        self.tbValve13.setObjectName(u"tbValve13")
        self.tbValve13.setGeometry(QRect(481, 519, 36, 35))
        self.tbValve12 = QPushButton(self.frmHeLine)
        self.tbValve12.setObjectName(u"tbValve12")
        self.tbValve12.setGeometry(QRect(316, 692, 36, 36))
        self.lblMS = QLabel(self.frmHeLine)
        self.lblMS.setObjectName(u"lblMS")
        self.lblMS.setGeometry(QRect(453, 6, 200, 20))
        self.lblMS.setFont(font)
        self.lblMS.setAlignment(Qt.AlignCenter)
        self.imgQMS = QFrame(self.frmHeLine)
        self.imgQMS.setObjectName(u"imgQMS")
        self.imgQMS.setGeometry(QRect(515, 24, 79, 111))
        self.imgQMS.setStyleSheet(u"image: url(:/main/QMS.png);")
        self.imgQMS.setFrameShape(QFrame.StyledPanel)
        self.imgQMS.setFrameShadow(QFrame.Raised)
        self.lcdElapsedTime = QLCDNumber(self.centralwidget)
        self.lcdElapsedTime.setObjectName(u"lcdElapsedTime")
        self.lcdElapsedTime.setGeometry(QRect(10, 5, 131, 41))
        self.lcdElapsedTime.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 45, 135, 21))
        self.label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 340, 251, 21))
        self.lblStatus = QLabel(self.centralwidget)
        self.lblStatus.setObjectName(u"lblStatus")
        self.lblStatus.setGeometry(QRect(330, 75, 571, 21))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 76, 191, 20))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 135, 171, 21))
        self.tbStop = QToolButton(self.centralwidget)
        self.tbStop.setObjectName(u"tbStop")
        self.tbStop.setGeometry(QRect(169, 820, 134, 134))
        self.tbStop.setStyleSheet(u"border-color: rgb(255, 255, 255);")
        icon1 = QIcon()
        icon1.addFile(u":/main/stop_up.png", QSize(), QIcon.Normal, QIcon.Off)
        icon1.addFile(u":/main/stop_down.png", QSize(), QIcon.Normal, QIcon.On)
        self.tbStop.setIcon(icon1)
        self.tbStop.setIconSize(QSize(154, 150))
        self.tbStop.setCheckable(True)
        self.tbStop.setPopupMode(QToolButton.DelayedPopup)
        self.tbStop.setAutoRaise(True)
        self.tbStop.setArrowType(Qt.NoArrow)
        self.tbRun = QToolButton(self.centralwidget)
        self.tbRun.setObjectName(u"tbRun")
        self.tbRun.setGeometry(QRect(10, 810, 84, 44))
        icon2 = QIcon()
        icon2.addFile(u":/main/run.png", QSize(), QIcon.Normal, QIcon.Off)
        icon2.addFile(u":/main/pause.png", QSize(), QIcon.Normal, QIcon.On)
        self.tbRun.setIcon(icon2)
        self.tbRun.setIconSize(QSize(84, 44))
        self.tbRun.setCheckable(True)
        self.listCommands = QListWidget(self.centralwidget)
        self.listCommands.setObjectName(u"listCommands")
        self.listCommands.setGeometry(QRect(10, 370, 301, 181))
        self.listCommands.setFont(font)
        self.listCommands.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(910, 46, 111, 21))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(1040, 46, 111, 21))
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(1170, 46, 111, 21))
        self.label_7.setStyleSheet(u"")
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 560, 251, 21))
        self.listBatch = QListWidget(self.centralwidget)
        self.listBatch.setObjectName(u"listBatch")
        self.listBatch.setGeometry(QRect(10, 590, 301, 211))
        self.listBatch.setFont(font)
        self.listBatch.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.listBatch.setModelColumn(0)
        self.linePlanchet = QLabel(self.centralwidget)
        self.linePlanchet.setObjectName(u"linePlanchet")
        self.linePlanchet.setGeometry(QRect(10, 100, 301, 30))
        self.linePlanchet.setFont(font)
        self.linePlanchet.setStyleSheet(u"background-color: rgb(255, 255, 255)")
        self.linePlanchet.setFrameShape(QFrame.Box)
        self.linePlanchet.setLineWidth(1)
        self.lineLocation = QLabel(self.centralwidget)
        self.lineLocation.setObjectName(u"lineLocation")
        self.lineLocation.setGeometry(QRect(10, 160, 301, 30))
        self.lineLocation.setFont(font)
        self.lineLocation.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineLocation.setFrameShape(QFrame.Box)
        self.lineIonPump = QLabel(self.centralwidget)
        self.lineIonPump.setObjectName(u"lineIonPump")
        self.lineIonPump.setGeometry(QRect(910, 5, 111, 41))
        font2 = QFont()
        font2.setFamily(u"Segoe UI")
        font2.setPointSize(14)
        font2.setBold(False)
        font2.setItalic(False)
        font2.setWeight(50)
        self.lineIonPump.setFont(font2)
        self.lineIonPump.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Segoe UI\";")
        self.lineIonPump.setFrameShape(QFrame.Box)
        self.lineIonPump.setLineWidth(1)
        self.lineTurboPump = QLabel(self.centralwidget)
        self.lineTurboPump.setObjectName(u"lineTurboPump")
        self.lineTurboPump.setGeometry(QRect(1040, 5, 111, 41))
        self.lineTurboPump.setFont(font2)
        self.lineTurboPump.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Segoe UI\";")
        self.lineTurboPump.setFrameShape(QFrame.Box)
        self.lineTurboPump.setLineWidth(1)
        self.lineScrollPump = QLabel(self.centralwidget)
        self.lineScrollPump.setObjectName(u"lineScrollPump")
        self.lineScrollPump.setGeometry(QRect(1170, 5, 111, 41))
        self.lineScrollPump.setFont(font2)
        self.lineScrollPump.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Segoe UI\";")
        self.lineScrollPump.setFrameShape(QFrame.Box)
        self.lineScrollPump.setLineWidth(1)
        self.lineXPosition = QLabel(self.centralwidget)
        self.lineXPosition.setObjectName(u"lineXPosition")
        self.lineXPosition.setGeometry(QRect(600, 5, 111, 41))
        self.lineXPosition.setFont(font2)
        self.lineXPosition.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Segoe UI\";")
        self.lineXPosition.setFrameShape(QFrame.Box)
        self.lineXPosition.setLineWidth(1)
        self.lineYPosition = QLabel(self.centralwidget)
        self.lineYPosition.setObjectName(u"lineYPosition")
        self.lineYPosition.setGeometry(QRect(730, 5, 111, 41))
        self.lineYPosition.setFont(font2)
        self.lineYPosition.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Segoe UI\";")
        self.lineYPosition.setFrameShape(QFrame.Box)
        self.lineYPosition.setLineWidth(1)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(600, 46, 111, 21))
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(730, 46, 111, 21))
        self.frmImage = QFrame(self.centralwidget)
        self.frmImage.setObjectName(u"frmImage")
        self.frmImage.setGeometry(QRect(331, 82, 950, 880))
        self.frmImage.setStyleSheet(u"image: url(:/main/main.png);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.frmImage.setFrameShape(QFrame.StyledPanel)
        self.frmImage.setFrameShadow(QFrame.Raised)
        self.lblCurrent = QLabel(self.centralwidget)
        self.lblCurrent.setObjectName(u"lblCurrent")
        self.lblCurrent.setGeometry(QRect(10, 200, 301, 121))
        self.lblCurrent.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.lblCurrent.setWordWrap(True)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(1290, 75, 151, 21))
        self.tableResults = QTableWidget(self.centralwidget)
        if (self.tableResults.columnCount() < 4):
            self.tableResults.setColumnCount(4)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.tableResults.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.tableResults.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.tableResults.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        __qtablewidgetitem3.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.tableResults.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        self.tableResults.setObjectName(u"tableResults")
        self.tableResults.setGeometry(QRect(1290, 100, 500, 851))
        self.tableResults.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(61, 61, 61);")
        self.tableResults.setLineWidth(2)
        self.tableResults.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.tableResults.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableResults.setDragDropOverwriteMode(False)
        self.tableResults.setAlternatingRowColors(True)
        self.tableResults.setSelectionMode(QAbstractItemView.ContiguousSelection)
        self.tableResults.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableResults.setTextElideMode(Qt.ElideLeft)
        self.tableResults.horizontalHeader().setStretchLastSection(False)
        self.tableResults.verticalHeader().setVisible(False)
        self.tableResults.verticalHeader().setHighlightSections(False)
        self.linePyrometer = QLabel(self.centralwidget)
        self.linePyrometer.setObjectName(u"linePyrometer")
        self.linePyrometer.setGeometry(QRect(1340, 5, 111, 41))
        self.linePyrometer.setFont(font2)
        self.linePyrometer.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Segoe UI\";")
        self.linePyrometer.setFrameShape(QFrame.Box)
        self.linePyrometer.setLineWidth(1)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(1340, 46, 111, 21))
        self.imgPyrometer = QFrame(self.centralwidget)
        self.imgPyrometer.setObjectName(u"imgPyrometer")
        self.imgPyrometer.setGeometry(QRect(1453, 5, 49, 41))
        self.imgPyrometer.setStyleSheet(u"image: url(:/main/pyrolaser.png);")
        self.imgPyrometer.setFrameShape(QFrame.NoFrame)
        self.imgPyrometer.setFrameShadow(QFrame.Plain)
        self.imgPyrometer.setLineWidth(0)
        self.lblAalarm = QLabel(self.centralwidget)
        self.lblAalarm.setObjectName(u"lblAalarm")
        self.lblAalarm.setGeometry(QRect(610, 850, 650, 90))
        font3 = QFont()
        font3.setFamily(u"Segoe UI")
        font3.setPointSize(12)
        font3.setBold(True)
        font3.setItalic(False)
        font3.setWeight(75)
        self.lblAalarm.setFont(font3)
        self.lblAalarm.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 600 12pt \"Segoe UI\";\n"
"color: rgb(255, 0, 0);\n"
"")
        self.lblAalarm.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.lblAalarm.setWordWrap(True)
        self.lblAalarm.setTextInteractionFlags(Qt.NoTextInteraction)
        MainWindow.setCentralWidget(self.centralwidget)
        self.frmImage.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.frmHeLine.raise_()
        self.lcdElapsedTime.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lblStatus.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.tbStop.raise_()
        self.tbRun.raise_()
        self.listCommands.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.listBatch.raise_()
        self.linePlanchet.raise_()
        self.lineLocation.raise_()
        self.lineIonPump.raise_()
        self.lineTurboPump.raise_()
        self.lineScrollPump.raise_()
        self.lineXPosition.raise_()
        self.lineYPosition.raise_()
        self.lblCurrent.raise_()
        self.label_11.raise_()
        self.tableResults.raise_()
        self.linePyrometer.raise_()
        self.label_12.raise_()
        self.imgPyrometer.raise_()
        self.lblAalarm.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1800, 29))
        self.menubar.setNativeMenuBar(True)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuBatch = QMenu(self.menubar)
        self.menuBatch.setObjectName(u"menuBatch")
        self.menuXYController = QMenu(self.menubar)
        self.menuXYController.setObjectName(u"menuXYController")
        self.menuValveController = QMenu(self.menubar)
        self.menuValveController.setObjectName(u"menuValveController")
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuPump_Reader = QMenu(self.menubar)
        self.menuPump_Reader.setObjectName(u"menuPump_Reader")
        MainWindow.setMenuBar(self.menubar)
        QWidget.setTabOrder(self.tbRun, self.listCommands)
        QWidget.setTabOrder(self.listCommands, self.listBatch)
        QWidget.setTabOrder(self.listBatch, self.spinLaserPower)
        QWidget.setTabOrder(self.spinLaserPower, self.tbStop)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBatch.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuXYController.menuAction())
        self.menubar.addAction(self.menuValveController.menuAction())
        self.menubar.addAction(self.menuPump_Reader.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionExit)
        self.menuBatch.addAction(self.actionStartNewBatch)
        self.menuXYController.addAction(self.actionXYOpenLogPage)
        self.menuXYController.addAction(self.actionXYOpenStatusPage)
        self.menuXYController.addSeparator()
        self.menuXYController.addAction(self.actionManualControl)
        self.menuValveController.addAction(self.actionValveOpenStatusPage)
        self.menuValveController.addAction(self.actionValveOpenLogPage)
        self.menuValveController.addSeparator()
        self.menuValveController.addAction(self.actionCO2LaserOn)
        self.menuValveController.addAction(self.actionCO2LaserOff)
        self.menuHelp.addAction(self.actionViewPyMSLog)
        self.menuHelp.addAction(self.actionViewPyMSSettings)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAboutPyMS)
        self.menuPump_Reader.addAction(self.actionPumpOpenStatusPage)
        self.menuPump_Reader.addAction(self.actionPumpOpenLogPage)
        self.menuPump_Reader.addSeparator()
        self.menuPump_Reader.addAction(self.actionPyroLaserOn)
        self.menuPump_Reader.addAction(self.actionPyroLaserOff)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"PyMS - Python Mass Spectrometry", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionStartNewBatch.setText(QCoreApplication.translate("MainWindow", u"Start New Batch", None))
#if QT_CONFIG(tooltip)
        self.actionStartNewBatch.setToolTip(QCoreApplication.translate("MainWindow", u"Create a new batch", None))
#endif // QT_CONFIG(tooltip)
        self.actionXYOpenStatusPage.setText(QCoreApplication.translate("MainWindow", u"Open Status Page", None))
        self.actionXYOpenLogPage.setText(QCoreApplication.translate("MainWindow", u"Open Log Page", None))
        self.actionValveOpenStatusPage.setText(QCoreApplication.translate("MainWindow", u"Open Status Page", None))
        self.actionValveOpenLogPage.setText(QCoreApplication.translate("MainWindow", u"Open Log Page", None))
        self.actionManualControl.setText(QCoreApplication.translate("MainWindow", u"Calibrate X-Y Stage", None))
        self.actionViewPyMSLog.setText(QCoreApplication.translate("MainWindow", u"View PyMS Log", None))
        self.actionAboutPyMS.setText(QCoreApplication.translate("MainWindow", u"About PyMS", None))
        self.actionViewPyMSSettings.setText(QCoreApplication.translate("MainWindow", u"Vew PyMS Settings", None))
        self.actionEdit_Cycle_Steps.setText(QCoreApplication.translate("MainWindow", u"Edit Cycle Steps", None))
        self.actionPumpOpenStatusPage.setText(QCoreApplication.translate("MainWindow", u"Open Sataus Page", None))
#if QT_CONFIG(tooltip)
        self.actionPumpOpenStatusPage.setToolTip(QCoreApplication.translate("MainWindow", u"Open Status Page", None))
#endif // QT_CONFIG(tooltip)
        self.actionPumpOpenLogPage.setText(QCoreApplication.translate("MainWindow", u"Open Log Page", None))
        self.actionPyroLaserOn.setText(QCoreApplication.translate("MainWindow", u"Pyrometer Laser On", None))
#if QT_CONFIG(tooltip)
        self.actionPyroLaserOn.setToolTip(QCoreApplication.translate("MainWindow", u"Switch on Pyrometer Location Laser", None))
#endif // QT_CONFIG(tooltip)
        self.actionPyroLaserOff.setText(QCoreApplication.translate("MainWindow", u"Pyrometer Laser Off", None))
#if QT_CONFIG(tooltip)
        self.actionPyroLaserOff.setToolTip(QCoreApplication.translate("MainWindow", u"Switch Off Pyrometer Location Laser", None))
#endif // QT_CONFIG(tooltip)
        self.actionCO2LaserOn.setText(QCoreApplication.translate("MainWindow", u"CO2 Laser On", None))
        self.actionCO2LaserOff.setText(QCoreApplication.translate("MainWindow", u"CO2 Laser Off", None))
#if QT_CONFIG(tooltip)
        self.frmHeLine.setToolTip(QCoreApplication.translate("MainWindow", u"Click on the valves to operate", None))
#endif // QT_CONFIG(tooltip)
        self.tbValve1.setText("")
        self.tbValve2.setText("")
        self.tbValve6.setText("")
        self.tbValve7.setText("")
        self.tbValve8.setText("")
        self.tbValve3.setText("")
        self.tbValve4.setText("")
        self.tbValve10.setText("")
        self.tbValve11.setText("")
        self.tbValve5.setText("")
        self.tbValve13.setText("")
        self.tbValve12.setText("")
        self.lblMS.setText(QCoreApplication.translate("MainWindow", u"OffLine", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Elapsed Time", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Remaining Commands", None))
        self.lblStatus.setText(QCoreApplication.translate("MainWindow", u"Status: Manual Control", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Batch", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Location / Sample", None))
#if QT_CONFIG(tooltip)
        self.tbStop.setToolTip(QCoreApplication.translate("MainWindow", u"Emergency STOP. Close all valves and switch off laser", None))
#endif // QT_CONFIG(tooltip)
        self.tbStop.setText("")
#if QT_CONFIG(tooltip)
        self.tbRun.setToolTip(QCoreApplication.translate("MainWindow", u"Press Run to start or Pause to halt at the end of currenct cycle", None))
#endif // QT_CONFIG(tooltip)
        self.tbRun.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Ion Gauge", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Turbo Gauge", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Tank Gauge", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Batch Items  (Currrent / Next)", None))
        self.linePlanchet.setText("")
        self.lineLocation.setText("")
        self.lineIonPump.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineTurboPump.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineScrollPump.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineXPosition.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineYPosition.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"X Position", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Y Position", None))
        self.lblCurrent.setText(QCoreApplication.translate("MainWindow", u"Current Command", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Results", None))
        ___qtablewidgetitem = self.tableResults.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Date", None));
        ___qtablewidgetitem1 = self.tableResults.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Data File", None));
        ___qtablewidgetitem2 = self.tableResults.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Sample", None));
        ___qtablewidgetitem3 = self.tableResults.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Best Fit", None));
        self.linePyrometer.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Pyrometer", None))
        self.lblAalarm.setText("")
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuBatch.setTitle(QCoreApplication.translate("MainWindow", u"Batch", None))
        self.menuXYController.setTitle(QCoreApplication.translate("MainWindow", u"X-Y Controller", None))
        self.menuValveController.setTitle(QCoreApplication.translate("MainWindow", u"Valve Controller", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u" | ", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Support", None))
        self.menuPump_Reader.setTitle(QCoreApplication.translate("MainWindow", u"Pump Reader", None))
    # retranslateUi

