# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'quadviewer.ui'
##
## Created by: Qt User Interface Compiler version 6.4.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QWidget)
import main_rc

class Ui_dialogQuadViewer(object):
    def setupUi(self, dialogQuadViewer):
        if not dialogQuadViewer.objectName():
            dialogQuadViewer.setObjectName(u"dialogQuadViewer")
        dialogQuadViewer.setWindowModality(Qt.ApplicationModal)
        dialogQuadViewer.setEnabled(True)
        dialogQuadViewer.resize(810, 500)
        dialogQuadViewer.setMinimumSize(QSize(810, 500))
        dialogQuadViewer.setMaximumSize(QSize(810, 500))
        icon = QIcon()
        icon.addFile(u":/main/iconGTRun.svg", QSize(), QIcon.Normal, QIcon.Off)
        dialogQuadViewer.setWindowIcon(icon)
        dialogQuadViewer.setStyleSheet(u"font: 10pt \"Segoe UI\";")
        self.frame = QFrame(dialogQuadViewer)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 811, 451))
        self.frame.setStyleSheet(u"font: 14pt \"Segoe UI\";")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_1 = QLabel(self.frame)
        self.label_1.setObjectName(u"label_1")
        self.label_1.setGeometry(QRect(10, 10, 141, 40))
        self.label_1.setScaledContents(True)
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 110, 91, 40))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_3 = QLabel(self.frame)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 160, 91, 40))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_4 = QLabel(self.frame)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 210, 91, 40))
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 260, 91, 40))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_7 = QLabel(self.frame)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 310, 101, 40))
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineM1 = QLineEdit(self.frame)
        self.lineM1.setObjectName(u"lineM1")
        self.lineM1.setGeometry(QRect(140, 110, 190, 40))
        self.lineM1.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.lineM1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineM3 = QLineEdit(self.frame)
        self.lineM3.setObjectName(u"lineM3")
        self.lineM3.setGeometry(QRect(140, 160, 190, 40))
        self.lineM3.setStyleSheet(u"color: rgb(0, 0, 255);")
        self.lineM3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineM4 = QLineEdit(self.frame)
        self.lineM4.setObjectName(u"lineM4")
        self.lineM4.setGeometry(QRect(140, 210, 190, 40))
        self.lineM4.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.lineM4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineM5 = QLineEdit(self.frame)
        self.lineM5.setObjectName(u"lineM5")
        self.lineM5.setGeometry(QRect(140, 260, 190, 40))
        self.lineM5.setStyleSheet(u"color: rgb(161, 161, 161);")
        self.lineM5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineM40 = QLineEdit(self.frame)
        self.lineM40.setObjectName(u"lineM40")
        self.lineM40.setGeometry(QRect(140, 310, 190, 40))
        self.lineM40.setStyleSheet(u"color: rgb(255, 0, 255);")
        self.lineM40.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lineDateTime = QLineEdit(self.frame)
        self.lineDateTime.setObjectName(u"lineDateTime")
        self.lineDateTime.setGeometry(QRect(170, 10, 391, 40))
        self.lineDateTime.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(140, 70, 190, 40))
        self.label.setScaledContents(True)
        self.label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_6 = QLabel(self.frame)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 70, 161, 40))
        self.label_6.setScaledContents(True)
        self.label_8 = QLabel(self.frame)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(450, 260, 130, 40))
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.line4He = QLineEdit(self.frame)
        self.line4He.setObjectName(u"line4He")
        self.line4He.setGeometry(QRect(590, 260, 190, 40))
        self.line4He.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line4He.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_9 = QLabel(self.frame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 390, 771, 51))
        self.label_9.setStyleSheet(u"font: 11pt \"Segoe UI\";")
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_9.setWordWrap(True)
        self.label_10 = QLabel(self.frame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(450, 110, 130, 40))
        self.label_10.setScaledContents(True)
        self.label_10.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lineHD = QLineEdit(self.frame)
        self.lineHD.setObjectName(u"lineHD")
        self.lineHD.setGeometry(QRect(590, 110, 190, 40))
        self.lineHD.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.lineHD.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.line3He = QLineEdit(self.frame)
        self.line3He.setObjectName(u"line3He")
        self.line3He.setGeometry(QRect(590, 160, 190, 40))
        self.line3He.setStyleSheet(u"color: rgb(0, 0, 0);")
        self.line3He.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_11 = QLabel(self.frame)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(450, 160, 130, 40))
        self.label_11.setScaledContents(True)
        self.label_11.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.btnReload = QPushButton(dialogQuadViewer)
        self.btnReload.setObjectName(u"btnReload")
        self.btnReload.setGeometry(QRect(610, 460, 80, 30))
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnReload.sizePolicy().hasHeightForWidth())
        self.btnReload.setSizePolicy(sizePolicy)
        self.btnReload.setAutoDefault(False)
        self.btnClose = QPushButton(dialogQuadViewer)
        self.btnClose.setObjectName(u"btnClose")
        self.btnClose.setGeometry(QRect(700, 460, 80, 30))
        self.btnClose.setAutoDefault(False)

        self.retranslateUi(dialogQuadViewer)

        self.btnReload.setDefault(False)
        self.btnClose.setDefault(False)


        QMetaObject.connectSlotsByName(dialogQuadViewer)
    # setupUi

    def retranslateUi(self, dialogQuadViewer):
        dialogQuadViewer.setWindowTitle(QCoreApplication.translate("dialogQuadViewer", u"Quad Viewer", None))
        self.label_1.setText(QCoreApplication.translate("dialogQuadViewer", u"Sample Time", None))
        self.label_2.setText(QCoreApplication.translate("dialogQuadViewer", u"M 1.09", None))
        self.label_3.setText(QCoreApplication.translate("dialogQuadViewer", u"M 3.03", None))
        self.label_4.setText(QCoreApplication.translate("dialogQuadViewer", u"M 4.03", None))
        self.label_5.setText(QCoreApplication.translate("dialogQuadViewer", u"M 5.03", None))
        self.label_7.setText(QCoreApplication.translate("dialogQuadViewer", u"M 40.16", None))
        self.lineM1.setText(QCoreApplication.translate("dialogQuadViewer", u"0.0", None))
        self.lineM3.setText(QCoreApplication.translate("dialogQuadViewer", u"0.0", None))
        self.lineM4.setText(QCoreApplication.translate("dialogQuadViewer", u"0.0", None))
        self.lineM5.setText(QCoreApplication.translate("dialogQuadViewer", u"0.0", None))
        self.lineM40.setText(QCoreApplication.translate("dialogQuadViewer", u"0.0", None))
        self.lineDateTime.setText(QCoreApplication.translate("dialogQuadViewer", u"dd/mm/yyyy hh:mm:ss", None))
        self.label.setText(QCoreApplication.translate("dialogQuadViewer", u"Current (A)", None))
        self.label_6.setText(QCoreApplication.translate("dialogQuadViewer", u"Mass", None))
        self.label_8.setText(QCoreApplication.translate("dialogQuadViewer", u"4He / 3He", None))
        self.line4He.setText(QCoreApplication.translate("dialogQuadViewer", u"0.0", None))
        self.label_9.setText(QCoreApplication.translate("dialogQuadViewer", u"Note: This is a rough calculated ratio based on a single sample and is not as accurate as a full sample such as a line blank or q-standard", None))
        self.label_10.setText(QCoreApplication.translate("dialogQuadViewer", u"HD (pA)", None))
        self.lineHD.setText(QCoreApplication.translate("dialogQuadViewer", u"0.0", None))
        self.line3He.setText(QCoreApplication.translate("dialogQuadViewer", u"0.0", None))
        self.label_11.setText(QCoreApplication.translate("dialogQuadViewer", u"3He (pA)", None))
        self.btnReload.setText(QCoreApplication.translate("dialogQuadViewer", u"Reload", None))
        self.btnClose.setText(QCoreApplication.translate("dialogQuadViewer", u"Close", None))
    # retranslateUi

