# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'cycleedit.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QComboBox,
    QDialog, QFrame, QHeaderView, QLabel,
    QLineEdit, QPlainTextEdit, QPushButton, QSizePolicy,
    QTableWidget, QTableWidgetItem, QWidget)
import main_rc

class Ui_dialogCycleEdit(object):
    def setupUi(self, dialogCycleEdit):
        if not dialogCycleEdit.objectName():
            dialogCycleEdit.setObjectName(u"dialogCycleEdit")
        dialogCycleEdit.resize(890, 900)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialogCycleEdit.sizePolicy().hasHeightForWidth())
        dialogCycleEdit.setSizePolicy(sizePolicy)
        dialogCycleEdit.setMinimumSize(QSize(890, 900))
        dialogCycleEdit.setMaximumSize(QSize(890, 900))
        icon = QIcon()
        icon.addFile(u":/main/iconPyMSRun.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        dialogCycleEdit.setWindowIcon(icon)
        dialogCycleEdit.setStyleSheet(u"font: 10pt \"Segoe UI\";")
        self.tableSteps = QTableWidget(dialogCycleEdit)
        if (self.tableSteps.columnCount() < 3):
            self.tableSteps.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.tableSteps.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.tableSteps.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.tableSteps.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        if (self.tableSteps.rowCount() < 10):
            self.tableSteps.setRowCount(10)
        self.tableSteps.setObjectName(u"tableSteps")
        self.tableSteps.setGeometry(QRect(10, 270, 530, 621))
        self.tableSteps.setStyleSheet(u"selection-background-color: rgb(197, 248, 255);\n"
"selection-color: rgb(0, 0, 0);\n"
"font: 10pt \"Segoe UI\";")
        self.tableSteps.setMidLineWidth(1)
        self.tableSteps.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableSteps.setDragDropOverwriteMode(False)
        self.tableSteps.setAlternatingRowColors(True)
        self.tableSteps.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableSteps.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableSteps.setTextElideMode(Qt.ElideLeft)
        self.tableSteps.setRowCount(10)
        self.tableSteps.setColumnCount(3)
        self.tableSteps.horizontalHeader().setVisible(True)
        self.tableSteps.horizontalHeader().setCascadingSectionResizes(False)
        self.tableSteps.horizontalHeader().setMinimumSectionSize(47)
        self.tableSteps.horizontalHeader().setDefaultSectionSize(130)
        self.tableSteps.verticalHeader().setVisible(False)
        self.comboCycles = QComboBox(dialogCycleEdit)
        self.comboCycles.setObjectName(u"comboCycles")
        self.comboCycles.setGeometry(QRect(10, 50, 300, 30))
        self.btnClose = QPushButton(dialogCycleEdit)
        self.btnClose.setObjectName(u"btnClose")
        self.btnClose.setGeometry(QRect(770, 860, 110, 35))
        self.textTime = QLineEdit(dialogCycleEdit)
        self.textTime.setObjectName(u"textTime")
        self.textTime.setGeometry(QRect(710, 270, 171, 30))
        self.label = QLabel(dialogCycleEdit)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(560, 270, 141, 30))
        self.label.setScaledContents(True)
        self.label_2 = QLabel(dialogCycleEdit)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(560, 330, 101, 30))
        self.label_2.setScaledContents(True)
        self.label_3 = QLabel(dialogCycleEdit)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(560, 390, 111, 30))
        self.label_3.setScaledContents(True)
        self.comboTarget = QComboBox(dialogCycleEdit)
        self.comboTarget.setObjectName(u"comboTarget")
        self.comboTarget.setGeometry(QRect(710, 330, 171, 30))
        self.comboCommand = QComboBox(dialogCycleEdit)
        self.comboCommand.setObjectName(u"comboCommand")
        self.comboCommand.setGeometry(QRect(710, 390, 171, 30))
        self.btnAdd = QPushButton(dialogCycleEdit)
        self.btnAdd.setObjectName(u"btnAdd")
        self.btnAdd.setGeometry(QRect(560, 460, 110, 35))
        self.btnDelete = QPushButton(dialogCycleEdit)
        self.btnDelete.setObjectName(u"btnDelete")
        self.btnDelete.setGeometry(QRect(770, 520, 110, 35))
        self.btnSaveSteps = QPushButton(dialogCycleEdit)
        self.btnSaveSteps.setObjectName(u"btnSaveSteps")
        self.btnSaveSteps.setGeometry(QRect(770, 570, 110, 35))
        self.btnRevert = QPushButton(dialogCycleEdit)
        self.btnRevert.setObjectName(u"btnRevert")
        self.btnRevert.setGeometry(QRect(560, 520, 110, 35))
        self.btnUpdate = QPushButton(dialogCycleEdit)
        self.btnUpdate.setObjectName(u"btnUpdate")
        self.btnUpdate.setGeometry(QRect(770, 460, 110, 35))
        self.label_4 = QLabel(dialogCycleEdit)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 20, 91, 21))
        self.label_4.setScaledContents(True)
        self.txtDescription = QPlainTextEdit(dialogCycleEdit)
        self.txtDescription.setObjectName(u"txtDescription")
        self.txtDescription.setGeometry(QRect(340, 50, 541, 70))
        self.label_5 = QLabel(dialogCycleEdit)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(340, 20, 91, 21))
        self.label_5.setScaledContents(True)
        self.chkEnabled = QCheckBox(dialogCycleEdit)
        self.chkEnabled.setObjectName(u"chkEnabled")
        self.chkEnabled.setGeometry(QRect(10, 100, 73, 20))
        self.chkSample = QCheckBox(dialogCycleEdit)
        self.chkSample.setObjectName(u"chkSample")
        self.chkSample.setGeometry(QRect(140, 100, 121, 20))
        self.line = QFrame(dialogCycleEdit)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 230, 869, 10))
        self.line.setFrameShadow(QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setMidLineWidth(1)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.txtLaserPower = QLineEdit(dialogCycleEdit)
        self.txtLaserPower.setObjectName(u"txtLaserPower")
        self.txtLaserPower.setGeometry(QRect(140, 140, 113, 21))
        self.label_6 = QLabel(dialogCycleEdit)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 140, 101, 16))
        self.label_7 = QLabel(dialogCycleEdit)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 240, 91, 21))
        self.label_7.setScaledContents(True)
        self.btnSaveCycle = QPushButton(dialogCycleEdit)
        self.btnSaveCycle.setObjectName(u"btnSaveCycle")
        self.btnSaveCycle.setGeometry(QRect(770, 180, 110, 35))
        self.btnDuplicate = QPushButton(dialogCycleEdit)
        self.btnDuplicate.setObjectName(u"btnDuplicate")
        self.btnDuplicate.setGeometry(QRect(560, 180, 110, 35))

        self.retranslateUi(dialogCycleEdit)

        self.btnClose.setDefault(True)


        QMetaObject.connectSlotsByName(dialogCycleEdit)
    # setupUi

    def retranslateUi(self, dialogCycleEdit):
        dialogCycleEdit.setWindowTitle(QCoreApplication.translate("dialogCycleEdit", u"PyMS - Cycle Editor", None))
        ___qtablewidgetitem = self.tableSteps.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("dialogCycleEdit", u"Time (s)", None));
        ___qtablewidgetitem1 = self.tableSteps.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("dialogCycleEdit", u"Target", None));
        ___qtablewidgetitem2 = self.tableSteps.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("dialogCycleEdit", u"Command", None));
#if QT_CONFIG(tooltip)
        self.comboCycles.setToolTip(QCoreApplication.translate("dialogCycleEdit", u"<html><head/><body><p>Select the cycle to edit</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnClose.setText(QCoreApplication.translate("dialogCycleEdit", u"Close", None))
        self.label.setText(QCoreApplication.translate("dialogCycleEdit", u"Time slot (seconds)", None))
        self.label_2.setText(QCoreApplication.translate("dialogCycleEdit", u"Target Device", None))
        self.label_3.setText(QCoreApplication.translate("dialogCycleEdit", u"Command", None))
#if QT_CONFIG(tooltip)
        self.btnAdd.setToolTip(QCoreApplication.translate("dialogCycleEdit", u"Add the task as a new one", None))
#endif // QT_CONFIG(tooltip)
        self.btnAdd.setText(QCoreApplication.translate("dialogCycleEdit", u"Add New", None))
#if QT_CONFIG(tooltip)
        self.btnDelete.setToolTip(QCoreApplication.translate("dialogCycleEdit", u"Delete selected task", None))
#endif // QT_CONFIG(tooltip)
        self.btnDelete.setText(QCoreApplication.translate("dialogCycleEdit", u"Delete Selected", None))
#if QT_CONFIG(tooltip)
        self.btnSaveSteps.setToolTip(QCoreApplication.translate("dialogCycleEdit", u"Save thesee changes to the database", None))
#endif // QT_CONFIG(tooltip)
        self.btnSaveSteps.setText(QCoreApplication.translate("dialogCycleEdit", u"Save Cycle", None))
#if QT_CONFIG(tooltip)
        self.btnRevert.setToolTip(QCoreApplication.translate("dialogCycleEdit", u"Cencel all changes and revert to exisitng cycle", None))
#endif // QT_CONFIG(tooltip)
        self.btnRevert.setText(QCoreApplication.translate("dialogCycleEdit", u"Revert", None))
#if QT_CONFIG(tooltip)
        self.btnUpdate.setToolTip(QCoreApplication.translate("dialogCycleEdit", u"Update existing task", None))
#endif // QT_CONFIG(tooltip)
        self.btnUpdate.setText(QCoreApplication.translate("dialogCycleEdit", u"Update Selected", None))
        self.label_4.setText(QCoreApplication.translate("dialogCycleEdit", u"Cycle", None))
        self.label_5.setText(QCoreApplication.translate("dialogCycleEdit", u"Description", None))
#if QT_CONFIG(tooltip)
        self.chkEnabled.setToolTip(QCoreApplication.translate("dialogCycleEdit", u"If checked will appear in simple batch screens", None))
#endif // QT_CONFIG(tooltip)
        self.chkEnabled.setText(QCoreApplication.translate("dialogCycleEdit", u"Enabled", None))
#if QT_CONFIG(tooltip)
        self.chkSample.setToolTip(QCoreApplication.translate("dialogCycleEdit", u"if checked will apper in planchet forms and will enable laser power settings", None))
#endif // QT_CONFIG(tooltip)
        self.chkSample.setText(QCoreApplication.translate("dialogCycleEdit", u"Enable Laser", None))
#if QT_CONFIG(tooltip)
        self.txtLaserPower.setToolTip(QCoreApplication.translate("dialogCycleEdit", u"Laser Power must be between o an 99.9 %", None))
#endif // QT_CONFIG(tooltip)
        self.label_6.setText(QCoreApplication.translate("dialogCycleEdit", u"Laser Power %", None))
        self.label_7.setText(QCoreApplication.translate("dialogCycleEdit", u"Cycle Steps", None))
#if QT_CONFIG(tooltip)
        self.btnSaveCycle.setToolTip(QCoreApplication.translate("dialogCycleEdit", u"Save thesee changes to the database", None))
#endif // QT_CONFIG(tooltip)
        self.btnSaveCycle.setText(QCoreApplication.translate("dialogCycleEdit", u"Save Details", None))
#if QT_CONFIG(tooltip)
        self.btnDuplicate.setToolTip(QCoreApplication.translate("dialogCycleEdit", u"<html><head/><body><p>Create a copy of the current cycle</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.btnDuplicate.setText(QCoreApplication.translate("dialogCycleEdit", u"Duplicate", None))
    # retranslateUi

