# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'simplebatch.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QWidget)
import main_rc

class Ui_dialogSimpleBatch(object):
    def setupUi(self, dialogSimpleBatch):
        if not dialogSimpleBatch.objectName():
            dialogSimpleBatch.setObjectName(u"dialogSimpleBatch")
        dialogSimpleBatch.setWindowModality(Qt.ApplicationModal)
        dialogSimpleBatch.setEnabled(True)
        dialogSimpleBatch.resize(810, 550)
        dialogSimpleBatch.setMinimumSize(QSize(808, 550))
        dialogSimpleBatch.setMaximumSize(QSize(810, 550))
        icon = QIcon()
        icon.addFile(u":/main/iconGTRun.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        dialogSimpleBatch.setWindowIcon(icon)
        dialogSimpleBatch.setStyleSheet(u"font: 10pt \"Segoe UI\";")
        self.comboTask1 = QComboBox(dialogSimpleBatch)
        self.comboTask1.setObjectName(u"comboTask1")
        self.comboTask1.setGeometry(QRect(50, 120, 200, 30))
        self.comboTask1.setEditable(False)
        self.comboTask1.setInsertPolicy(QComboBox.InsertAtTop)
        self.comboTask1.setMinimumContentsLength(0)
        self.label = QLabel(dialogSimpleBatch)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(50, 90, 47, 20))
        self.label.setScaledContents(True)
        self.label_2 = QLabel(dialogSimpleBatch)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(272, 90, 200, 20))
        self.label_2.setScaledContents(True)
        self.label_3 = QLabel(dialogSimpleBatch)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(485, 90, 310, 20))
        self.label_3.setScaledContents(True)
        self.comboLocation1 = QComboBox(dialogSimpleBatch)
        self.comboLocation1.setObjectName(u"comboLocation1")
        self.comboLocation1.setEnabled(False)
        self.comboLocation1.setGeometry(QRect(272, 120, 200, 30))
        self.comboLocation1.setEditable(False)
        self.comboLocation1.setInsertPolicy(QComboBox.InsertAtBottom)
        self.lineSample1 = QLineEdit(dialogSimpleBatch)
        self.lineSample1.setObjectName(u"lineSample1")
        self.lineSample1.setEnabled(False)
        self.lineSample1.setGeometry(QRect(485, 120, 310, 30))
        self.label_4 = QLabel(dialogSimpleBatch)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 120, 16, 30))
        self.lineSample2 = QLineEdit(dialogSimpleBatch)
        self.lineSample2.setObjectName(u"lineSample2")
        self.lineSample2.setEnabled(False)
        self.lineSample2.setGeometry(QRect(485, 160, 310, 30))
        self.comboLocation2 = QComboBox(dialogSimpleBatch)
        self.comboLocation2.setObjectName(u"comboLocation2")
        self.comboLocation2.setEnabled(False)
        self.comboLocation2.setGeometry(QRect(272, 160, 200, 30))
        self.comboLocation2.setEditable(False)
        self.comboLocation2.setInsertPolicy(QComboBox.InsertAtBottom)
        self.comboTask2 = QComboBox(dialogSimpleBatch)
        self.comboTask2.setObjectName(u"comboTask2")
        self.comboTask2.setEnabled(False)
        self.comboTask2.setGeometry(QRect(50, 160, 200, 30))
        self.comboTask2.setEditable(False)
        self.comboTask2.setInsertPolicy(QComboBox.InsertAtTop)
        self.comboTask2.setMinimumContentsLength(0)
        self.label_5 = QLabel(dialogSimpleBatch)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 160, 16, 30))
        self.lineSample3 = QLineEdit(dialogSimpleBatch)
        self.lineSample3.setObjectName(u"lineSample3")
        self.lineSample3.setEnabled(False)
        self.lineSample3.setGeometry(QRect(485, 200, 310, 30))
        self.comboLocation3 = QComboBox(dialogSimpleBatch)
        self.comboLocation3.setObjectName(u"comboLocation3")
        self.comboLocation3.setEnabled(False)
        self.comboLocation3.setGeometry(QRect(272, 200, 200, 30))
        self.comboLocation3.setEditable(False)
        self.comboLocation3.setInsertPolicy(QComboBox.InsertAtBottom)
        self.comboTask3 = QComboBox(dialogSimpleBatch)
        self.comboTask3.setObjectName(u"comboTask3")
        self.comboTask3.setEnabled(False)
        self.comboTask3.setGeometry(QRect(50, 200, 200, 30))
        self.comboTask3.setEditable(False)
        self.comboTask3.setInsertPolicy(QComboBox.InsertAtTop)
        self.comboTask3.setMinimumContentsLength(0)
        self.label_6 = QLabel(dialogSimpleBatch)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 200, 16, 30))
        self.lineSample4 = QLineEdit(dialogSimpleBatch)
        self.lineSample4.setObjectName(u"lineSample4")
        self.lineSample4.setEnabled(False)
        self.lineSample4.setGeometry(QRect(485, 240, 310, 30))
        self.comboLocation4 = QComboBox(dialogSimpleBatch)
        self.comboLocation4.setObjectName(u"comboLocation4")
        self.comboLocation4.setEnabled(False)
        self.comboLocation4.setGeometry(QRect(272, 240, 200, 30))
        self.comboLocation4.setEditable(False)
        self.comboLocation4.setInsertPolicy(QComboBox.InsertAtBottom)
        self.comboTask4 = QComboBox(dialogSimpleBatch)
        self.comboTask4.setObjectName(u"comboTask4")
        self.comboTask4.setEnabled(False)
        self.comboTask4.setGeometry(QRect(50, 240, 200, 30))
        self.comboTask4.setEditable(False)
        self.comboTask4.setInsertPolicy(QComboBox.InsertAtTop)
        self.comboTask4.setMinimumContentsLength(0)
        self.label_7 = QLabel(dialogSimpleBatch)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 240, 16, 30))
        self.lineSample5 = QLineEdit(dialogSimpleBatch)
        self.lineSample5.setObjectName(u"lineSample5")
        self.lineSample5.setEnabled(False)
        self.lineSample5.setGeometry(QRect(485, 280, 310, 30))
        self.comboLocation5 = QComboBox(dialogSimpleBatch)
        self.comboLocation5.setObjectName(u"comboLocation5")
        self.comboLocation5.setEnabled(False)
        self.comboLocation5.setGeometry(QRect(272, 280, 200, 30))
        self.comboLocation5.setEditable(False)
        self.comboLocation5.setInsertPolicy(QComboBox.InsertAtBottom)
        self.comboTask5 = QComboBox(dialogSimpleBatch)
        self.comboTask5.setObjectName(u"comboTask5")
        self.comboTask5.setEnabled(False)
        self.comboTask5.setGeometry(QRect(50, 280, 200, 30))
        self.comboTask5.setEditable(False)
        self.comboTask5.setInsertPolicy(QComboBox.InsertAtTop)
        self.comboTask5.setMinimumContentsLength(0)
        self.label_8 = QLabel(dialogSimpleBatch)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 280, 16, 30))
        self.labelError = QLabel(dialogSimpleBatch)
        self.labelError.setObjectName(u"labelError")
        self.labelError.setGeometry(QRect(20, 460, 571, 71))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.labelError.setFont(font)
        self.labelError.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.labelError.setScaledContents(True)
        self.labelError.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.labelError.setWordWrap(True)
        self.label_9 = QLabel(dialogSimpleBatch)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 50, 171, 30))
        self.label_9.setScaledContents(True)
        self.lineDescription = QLineEdit(dialogSimpleBatch)
        self.lineDescription.setObjectName(u"lineDescription")
        self.lineDescription.setGeometry(QRect(190, 50, 611, 30))
        self.label_10 = QLabel(dialogSimpleBatch)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 10, 171, 30))
        self.label_10.setScaledContents(True)
        self.lineDate = QLineEdit(dialogSimpleBatch)
        self.lineDate.setObjectName(u"lineDate")
        self.lineDate.setEnabled(True)
        self.lineDate.setGeometry(QRect(190, 10, 611, 30))
        self.lineDate.setStyleSheet(u"")
        self.lineDate.setReadOnly(True)
        self.btnClose = QPushButton(dialogSimpleBatch)
        self.btnClose.setObjectName(u"btnClose")
        self.btnClose.setGeometry(QRect(700, 510, 80, 30))
        self.btnClose.setAutoDefault(False)
        self.btnSave = QPushButton(dialogSimpleBatch)
        self.btnSave.setObjectName(u"btnSave")
        self.btnSave.setEnabled(True)
        self.btnSave.setGeometry(QRect(610, 510, 80, 30))
        self.lineSample6 = QLineEdit(dialogSimpleBatch)
        self.lineSample6.setObjectName(u"lineSample6")
        self.lineSample6.setEnabled(False)
        self.lineSample6.setGeometry(QRect(483, 320, 310, 30))
        self.label_11 = QLabel(dialogSimpleBatch)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(8, 320, 16, 30))
        self.comboTask6 = QComboBox(dialogSimpleBatch)
        self.comboTask6.setObjectName(u"comboTask6")
        self.comboTask6.setEnabled(False)
        self.comboTask6.setGeometry(QRect(48, 320, 200, 30))
        self.comboTask6.setEditable(False)
        self.comboTask6.setInsertPolicy(QComboBox.InsertAtTop)
        self.comboTask6.setMinimumContentsLength(0)
        self.comboLocation6 = QComboBox(dialogSimpleBatch)
        self.comboLocation6.setObjectName(u"comboLocation6")
        self.comboLocation6.setEnabled(False)
        self.comboLocation6.setGeometry(QRect(270, 320, 200, 30))
        self.comboLocation6.setEditable(False)
        self.comboLocation6.setInsertPolicy(QComboBox.InsertAtBottom)
        self.lineSample7 = QLineEdit(dialogSimpleBatch)
        self.lineSample7.setObjectName(u"lineSample7")
        self.lineSample7.setEnabled(False)
        self.lineSample7.setGeometry(QRect(483, 360, 310, 30))
        self.label_12 = QLabel(dialogSimpleBatch)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(8, 360, 16, 30))
        self.comboTask7 = QComboBox(dialogSimpleBatch)
        self.comboTask7.setObjectName(u"comboTask7")
        self.comboTask7.setEnabled(False)
        self.comboTask7.setGeometry(QRect(48, 360, 200, 30))
        self.comboTask7.setEditable(False)
        self.comboTask7.setInsertPolicy(QComboBox.InsertAtTop)
        self.comboTask7.setMinimumContentsLength(0)
        self.comboLocation7 = QComboBox(dialogSimpleBatch)
        self.comboLocation7.setObjectName(u"comboLocation7")
        self.comboLocation7.setEnabled(False)
        self.comboLocation7.setGeometry(QRect(270, 360, 200, 30))
        self.comboLocation7.setEditable(False)
        self.comboLocation7.setInsertPolicy(QComboBox.InsertAtBottom)
        self.lineSample8 = QLineEdit(dialogSimpleBatch)
        self.lineSample8.setObjectName(u"lineSample8")
        self.lineSample8.setEnabled(False)
        self.lineSample8.setGeometry(QRect(483, 400, 310, 30))
        self.label_13 = QLabel(dialogSimpleBatch)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(8, 400, 16, 30))
        self.comboTask8 = QComboBox(dialogSimpleBatch)
        self.comboTask8.setObjectName(u"comboTask8")
        self.comboTask8.setEnabled(False)
        self.comboTask8.setGeometry(QRect(48, 400, 200, 30))
        self.comboTask8.setEditable(False)
        self.comboTask8.setInsertPolicy(QComboBox.InsertAtTop)
        self.comboTask8.setMinimumContentsLength(0)
        self.comboLocation8 = QComboBox(dialogSimpleBatch)
        self.comboLocation8.setObjectName(u"comboLocation8")
        self.comboLocation8.setEnabled(False)
        self.comboLocation8.setGeometry(QRect(270, 400, 200, 30))
        self.comboLocation8.setEditable(False)
        self.comboLocation8.setInsertPolicy(QComboBox.InsertAtBottom)
        QWidget.setTabOrder(self.lineDescription, self.comboTask1)
        QWidget.setTabOrder(self.comboTask1, self.comboLocation1)
        QWidget.setTabOrder(self.comboLocation1, self.lineSample1)
        QWidget.setTabOrder(self.lineSample1, self.comboTask2)
        QWidget.setTabOrder(self.comboTask2, self.comboLocation2)
        QWidget.setTabOrder(self.comboLocation2, self.lineSample2)
        QWidget.setTabOrder(self.lineSample2, self.comboTask3)
        QWidget.setTabOrder(self.comboTask3, self.comboLocation3)
        QWidget.setTabOrder(self.comboLocation3, self.lineSample3)
        QWidget.setTabOrder(self.lineSample3, self.comboTask4)
        QWidget.setTabOrder(self.comboTask4, self.comboLocation4)
        QWidget.setTabOrder(self.comboLocation4, self.lineSample4)
        QWidget.setTabOrder(self.lineSample4, self.comboTask5)
        QWidget.setTabOrder(self.comboTask5, self.comboLocation5)
        QWidget.setTabOrder(self.comboLocation5, self.lineSample5)
        QWidget.setTabOrder(self.lineSample5, self.btnSave)
        QWidget.setTabOrder(self.btnSave, self.btnClose)
        QWidget.setTabOrder(self.btnClose, self.lineDate)

        self.retranslateUi(dialogSimpleBatch)

        self.comboTask1.setCurrentIndex(-1)
        self.comboLocation1.setCurrentIndex(-1)
        self.comboLocation2.setCurrentIndex(-1)
        self.comboTask2.setCurrentIndex(-1)
        self.comboLocation3.setCurrentIndex(-1)
        self.comboTask3.setCurrentIndex(-1)
        self.comboLocation4.setCurrentIndex(-1)
        self.comboTask4.setCurrentIndex(-1)
        self.comboLocation5.setCurrentIndex(-1)
        self.comboTask5.setCurrentIndex(-1)
        self.btnClose.setDefault(False)
        self.comboTask6.setCurrentIndex(-1)
        self.comboLocation6.setCurrentIndex(-1)
        self.comboTask7.setCurrentIndex(-1)
        self.comboLocation7.setCurrentIndex(-1)
        self.comboTask8.setCurrentIndex(-1)
        self.comboLocation8.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(dialogSimpleBatch)
    # setupUi

    def retranslateUi(self, dialogSimpleBatch):
        dialogSimpleBatch.setWindowTitle(QCoreApplication.translate("dialogSimpleBatch", u"New Simple Batch", None))
        self.label.setText(QCoreApplication.translate("dialogSimpleBatch", u"Task", None))
        self.label_2.setText(QCoreApplication.translate("dialogSimpleBatch", u"Location", None))
        self.label_3.setText(QCoreApplication.translate("dialogSimpleBatch", u"Sample Reference", None))
        self.comboLocation1.setCurrentText("")
        self.label_4.setText(QCoreApplication.translate("dialogSimpleBatch", u"1", None))
        self.comboLocation2.setCurrentText("")
        self.label_5.setText(QCoreApplication.translate("dialogSimpleBatch", u"2", None))
        self.comboLocation3.setCurrentText("")
        self.label_6.setText(QCoreApplication.translate("dialogSimpleBatch", u"3", None))
        self.comboLocation4.setCurrentText("")
        self.label_7.setText(QCoreApplication.translate("dialogSimpleBatch", u"4", None))
        self.comboLocation5.setCurrentText("")
        self.label_8.setText(QCoreApplication.translate("dialogSimpleBatch", u"5", None))
        self.labelError.setText("")
        self.label_9.setText(QCoreApplication.translate("dialogSimpleBatch", u"Description", None))
        self.label_10.setText(QCoreApplication.translate("dialogSimpleBatch", u"Date Created", None))
        self.btnClose.setText(QCoreApplication.translate("dialogSimpleBatch", u"Close", None))
        self.btnSave.setText(QCoreApplication.translate("dialogSimpleBatch", u"Save", None))
        self.label_11.setText(QCoreApplication.translate("dialogSimpleBatch", u"6", None))
        self.comboLocation6.setCurrentText("")
        self.label_12.setText(QCoreApplication.translate("dialogSimpleBatch", u"7", None))
        self.comboLocation7.setCurrentText("")
        self.label_13.setText(QCoreApplication.translate("dialogSimpleBatch", u"8", None))
        self.comboLocation8.setCurrentText("")
    # retranslateUi

