# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'planchetbatch.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QWidget)
import main_rc

class Ui_dialogPlanchet(object):
    def setupUi(self, dialogPlanchet):
        if not dialogPlanchet.objectName():
            dialogPlanchet.setObjectName(u"dialogPlanchet")
        dialogPlanchet.resize(1100, 750)
        icon = QIcon()
        icon.addFile(u":/main/iconGTRun.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon.addFile(u":/main/iconGTRun.svg", QSize(), QIcon.Mode.Disabled, QIcon.State.Off)
        icon.addFile(u":/main/iconGTRun.svg", QSize(), QIcon.Mode.Selected, QIcon.State.Off)
        dialogPlanchet.setWindowIcon(icon)
        dialogPlanchet.setStyleSheet(u"font: 10pt \"Segoe UI\";")
        dialogPlanchet.setModal(True)
        self.lineS1 = QLineEdit(dialogPlanchet)
        self.lineS1.setObjectName(u"lineS1")
        self.lineS1.setGeometry(QRect(350, 140, 100, 30))
        self.lineS2 = QLineEdit(dialogPlanchet)
        self.lineS2.setObjectName(u"lineS2")
        self.lineS2.setGeometry(QRect(490, 140, 100, 30))
        self.lineS3 = QLineEdit(dialogPlanchet)
        self.lineS3.setObjectName(u"lineS3")
        self.lineS3.setGeometry(QRect(630, 140, 100, 30))
        self.lineA3 = QLineEdit(dialogPlanchet)
        self.lineA3.setObjectName(u"lineA3")
        self.lineA3.setGeometry(QRect(350, 220, 100, 30))
        self.lineA4 = QLineEdit(dialogPlanchet)
        self.lineA4.setObjectName(u"lineA4")
        self.lineA4.setGeometry(QRect(490, 220, 100, 30))
        self.lineA2 = QLineEdit(dialogPlanchet)
        self.lineA2.setObjectName(u"lineA2")
        self.lineA2.setGeometry(QRect(210, 220, 100, 30))
        self.lineA6 = QLineEdit(dialogPlanchet)
        self.lineA6.setObjectName(u"lineA6")
        self.lineA6.setGeometry(QRect(770, 220, 100, 30))
        self.lineA7 = QLineEdit(dialogPlanchet)
        self.lineA7.setObjectName(u"lineA7")
        self.lineA7.setGeometry(QRect(910, 220, 100, 30))
        self.lineA5 = QLineEdit(dialogPlanchet)
        self.lineA5.setObjectName(u"lineA5")
        self.lineA5.setGeometry(QRect(630, 220, 100, 30))
        self.lineA1 = QLineEdit(dialogPlanchet)
        self.lineA1.setObjectName(u"lineA1")
        self.lineA1.setGeometry(QRect(70, 220, 100, 30))
        self.lineB6 = QLineEdit(dialogPlanchet)
        self.lineB6.setObjectName(u"lineB6")
        self.lineB6.setGeometry(QRect(770, 270, 100, 30))
        self.lineB2 = QLineEdit(dialogPlanchet)
        self.lineB2.setObjectName(u"lineB2")
        self.lineB2.setGeometry(QRect(210, 270, 100, 30))
        self.lineB5 = QLineEdit(dialogPlanchet)
        self.lineB5.setObjectName(u"lineB5")
        self.lineB5.setGeometry(QRect(630, 270, 100, 30))
        self.lineB3 = QLineEdit(dialogPlanchet)
        self.lineB3.setObjectName(u"lineB3")
        self.lineB3.setGeometry(QRect(350, 270, 100, 30))
        self.lineB7 = QLineEdit(dialogPlanchet)
        self.lineB7.setObjectName(u"lineB7")
        self.lineB7.setGeometry(QRect(910, 270, 100, 30))
        self.lineB1 = QLineEdit(dialogPlanchet)
        self.lineB1.setObjectName(u"lineB1")
        self.lineB1.setGeometry(QRect(70, 270, 100, 30))
        self.lineB4 = QLineEdit(dialogPlanchet)
        self.lineB4.setObjectName(u"lineB4")
        self.lineB4.setGeometry(QRect(490, 270, 100, 30))
        self.lineC6 = QLineEdit(dialogPlanchet)
        self.lineC6.setObjectName(u"lineC6")
        self.lineC6.setGeometry(QRect(770, 320, 100, 30))
        self.lineC2 = QLineEdit(dialogPlanchet)
        self.lineC2.setObjectName(u"lineC2")
        self.lineC2.setGeometry(QRect(210, 320, 100, 30))
        self.lineC5 = QLineEdit(dialogPlanchet)
        self.lineC5.setObjectName(u"lineC5")
        self.lineC5.setGeometry(QRect(630, 320, 100, 30))
        self.lineC3 = QLineEdit(dialogPlanchet)
        self.lineC3.setObjectName(u"lineC3")
        self.lineC3.setGeometry(QRect(350, 320, 100, 30))
        self.lineC7 = QLineEdit(dialogPlanchet)
        self.lineC7.setObjectName(u"lineC7")
        self.lineC7.setGeometry(QRect(910, 320, 100, 30))
        self.lineC1 = QLineEdit(dialogPlanchet)
        self.lineC1.setObjectName(u"lineC1")
        self.lineC1.setGeometry(QRect(70, 320, 100, 30))
        self.lineC4 = QLineEdit(dialogPlanchet)
        self.lineC4.setObjectName(u"lineC4")
        self.lineC4.setGeometry(QRect(490, 320, 100, 30))
        self.lineD6 = QLineEdit(dialogPlanchet)
        self.lineD6.setObjectName(u"lineD6")
        self.lineD6.setGeometry(QRect(770, 370, 100, 30))
        self.lineD2 = QLineEdit(dialogPlanchet)
        self.lineD2.setObjectName(u"lineD2")
        self.lineD2.setGeometry(QRect(210, 370, 100, 30))
        self.lineD5 = QLineEdit(dialogPlanchet)
        self.lineD5.setObjectName(u"lineD5")
        self.lineD5.setGeometry(QRect(630, 370, 100, 30))
        self.lineD3 = QLineEdit(dialogPlanchet)
        self.lineD3.setObjectName(u"lineD3")
        self.lineD3.setGeometry(QRect(350, 370, 100, 30))
        self.lineD7 = QLineEdit(dialogPlanchet)
        self.lineD7.setObjectName(u"lineD7")
        self.lineD7.setGeometry(QRect(910, 370, 100, 30))
        self.lineD1 = QLineEdit(dialogPlanchet)
        self.lineD1.setObjectName(u"lineD1")
        self.lineD1.setGeometry(QRect(70, 370, 100, 30))
        self.lineD4 = QLineEdit(dialogPlanchet)
        self.lineD4.setObjectName(u"lineD4")
        self.lineD4.setGeometry(QRect(490, 370, 100, 30))
        self.lineE6 = QLineEdit(dialogPlanchet)
        self.lineE6.setObjectName(u"lineE6")
        self.lineE6.setGeometry(QRect(770, 420, 100, 30))
        self.lineE2 = QLineEdit(dialogPlanchet)
        self.lineE2.setObjectName(u"lineE2")
        self.lineE2.setGeometry(QRect(210, 420, 100, 30))
        self.lineE5 = QLineEdit(dialogPlanchet)
        self.lineE5.setObjectName(u"lineE5")
        self.lineE5.setGeometry(QRect(630, 420, 100, 30))
        self.lineE3 = QLineEdit(dialogPlanchet)
        self.lineE3.setObjectName(u"lineE3")
        self.lineE3.setGeometry(QRect(350, 420, 100, 30))
        self.lineE7 = QLineEdit(dialogPlanchet)
        self.lineE7.setObjectName(u"lineE7")
        self.lineE7.setGeometry(QRect(910, 420, 100, 30))
        self.lineE1 = QLineEdit(dialogPlanchet)
        self.lineE1.setObjectName(u"lineE1")
        self.lineE1.setGeometry(QRect(70, 420, 100, 30))
        self.lineE4 = QLineEdit(dialogPlanchet)
        self.lineE4.setObjectName(u"lineE4")
        self.lineE4.setGeometry(QRect(490, 420, 100, 30))
        self.lineF6 = QLineEdit(dialogPlanchet)
        self.lineF6.setObjectName(u"lineF6")
        self.lineF6.setGeometry(QRect(770, 470, 100, 30))
        self.lineF2 = QLineEdit(dialogPlanchet)
        self.lineF2.setObjectName(u"lineF2")
        self.lineF2.setGeometry(QRect(210, 470, 100, 30))
        self.lineF5 = QLineEdit(dialogPlanchet)
        self.lineF5.setObjectName(u"lineF5")
        self.lineF5.setGeometry(QRect(630, 470, 100, 30))
        self.lineF3 = QLineEdit(dialogPlanchet)
        self.lineF3.setObjectName(u"lineF3")
        self.lineF3.setGeometry(QRect(350, 470, 100, 30))
        self.lineF7 = QLineEdit(dialogPlanchet)
        self.lineF7.setObjectName(u"lineF7")
        self.lineF7.setGeometry(QRect(910, 470, 100, 30))
        self.lineF1 = QLineEdit(dialogPlanchet)
        self.lineF1.setObjectName(u"lineF1")
        self.lineF1.setGeometry(QRect(70, 470, 100, 30))
        self.lineF4 = QLineEdit(dialogPlanchet)
        self.lineF4.setObjectName(u"lineF4")
        self.lineF4.setGeometry(QRect(490, 470, 100, 30))
        self.lineG6 = QLineEdit(dialogPlanchet)
        self.lineG6.setObjectName(u"lineG6")
        self.lineG6.setGeometry(QRect(770, 520, 100, 30))
        self.lineG2 = QLineEdit(dialogPlanchet)
        self.lineG2.setObjectName(u"lineG2")
        self.lineG2.setGeometry(QRect(210, 520, 100, 30))
        self.lineG5 = QLineEdit(dialogPlanchet)
        self.lineG5.setObjectName(u"lineG5")
        self.lineG5.setGeometry(QRect(630, 520, 100, 30))
        self.lineG3 = QLineEdit(dialogPlanchet)
        self.lineG3.setObjectName(u"lineG3")
        self.lineG3.setGeometry(QRect(350, 520, 100, 30))
        self.lineG7 = QLineEdit(dialogPlanchet)
        self.lineG7.setObjectName(u"lineG7")
        self.lineG7.setGeometry(QRect(910, 520, 100, 30))
        self.lineG1 = QLineEdit(dialogPlanchet)
        self.lineG1.setObjectName(u"lineG1")
        self.lineG1.setGeometry(QRect(70, 520, 100, 30))
        self.lineG4 = QLineEdit(dialogPlanchet)
        self.lineG4.setObjectName(u"lineG4")
        self.lineG4.setGeometry(QRect(490, 520, 100, 30))
        self.lineS5 = QLineEdit(dialogPlanchet)
        self.lineS5.setObjectName(u"lineS5")
        self.lineS5.setGeometry(QRect(490, 600, 100, 30))
        self.lineS6 = QLineEdit(dialogPlanchet)
        self.lineS6.setObjectName(u"lineS6")
        self.lineS6.setGeometry(QRect(630, 600, 100, 30))
        self.lineS4 = QLineEdit(dialogPlanchet)
        self.lineS4.setObjectName(u"lineS4")
        self.lineS4.setGeometry(QRect(350, 600, 100, 30))
        self.lineDescription = QLineEdit(dialogPlanchet)
        self.lineDescription.setObjectName(u"lineDescription")
        self.lineDescription.setGeometry(QRect(150, 70, 911, 30))
        self.label_9 = QLabel(dialogPlanchet)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 70, 121, 30))
        self.label_9.setScaledContents(True)
        self.label_10 = QLabel(dialogPlanchet)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 30, 121, 30))
        self.label_10.setScaledContents(True)
        self.lineDate = QLineEdit(dialogPlanchet)
        self.lineDate.setObjectName(u"lineDate")
        self.lineDate.setEnabled(True)
        self.lineDate.setGeometry(QRect(150, 30, 381, 30))
        self.lineDate.setStyleSheet(u"")
        self.lineDate.setReadOnly(True)
        self.label = QLabel(dialogPlanchet)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(390, 110, 20, 13))
        self.label.setScaledContents(True)
        self.label.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(dialogPlanchet)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(530, 110, 20, 13))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(dialogPlanchet)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(670, 110, 20, 13))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(dialogPlanchet)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 220, 20, 13))
        self.label_4.setScaledContents(True)
        self.label_5 = QLabel(dialogPlanchet)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(30, 270, 20, 13))
        self.label_5.setScaledContents(True)
        self.label_6 = QLabel(dialogPlanchet)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 320, 20, 13))
        self.label_6.setScaledContents(True)
        self.label_7 = QLabel(dialogPlanchet)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(30, 370, 20, 13))
        self.label_7.setScaledContents(True)
        self.label_8 = QLabel(dialogPlanchet)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 420, 20, 13))
        self.label_8.setScaledContents(True)
        self.label_11 = QLabel(dialogPlanchet)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(30, 470, 20, 13))
        self.label_11.setScaledContents(True)
        self.label_12 = QLabel(dialogPlanchet)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(30, 520, 20, 13))
        self.label_12.setScaledContents(True)
        self.label_13 = QLabel(dialogPlanchet)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(110, 190, 20, 13))
        self.label_13.setScaledContents(True)
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_14 = QLabel(dialogPlanchet)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(250, 190, 20, 13))
        self.label_14.setScaledContents(True)
        self.label_14.setAlignment(Qt.AlignCenter)
        self.label_15 = QLabel(dialogPlanchet)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(390, 190, 20, 13))
        self.label_15.setScaledContents(True)
        self.label_15.setAlignment(Qt.AlignCenter)
        self.label_16 = QLabel(dialogPlanchet)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(530, 190, 20, 13))
        self.label_16.setScaledContents(True)
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_17 = QLabel(dialogPlanchet)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(670, 190, 20, 13))
        self.label_17.setScaledContents(True)
        self.label_17.setAlignment(Qt.AlignCenter)
        self.label_18 = QLabel(dialogPlanchet)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(810, 190, 20, 13))
        self.label_18.setScaledContents(True)
        self.label_18.setAlignment(Qt.AlignCenter)
        self.label_19 = QLabel(dialogPlanchet)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(950, 190, 20, 13))
        self.label_19.setScaledContents(True)
        self.label_19.setAlignment(Qt.AlignCenter)
        self.label_20 = QLabel(dialogPlanchet)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(1050, 230, 20, 13))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.label_20.setFont(font)
        self.label_20.setScaledContents(True)
        self.label_21 = QLabel(dialogPlanchet)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(1050, 280, 20, 13))
        self.label_21.setFont(font)
        self.label_21.setScaledContents(True)
        self.label_22 = QLabel(dialogPlanchet)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(1050, 330, 20, 13))
        self.label_22.setFont(font)
        self.label_22.setScaledContents(True)
        self.label_23 = QLabel(dialogPlanchet)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(1050, 380, 20, 13))
        self.label_23.setFont(font)
        self.label_23.setScaledContents(True)
        self.label_24 = QLabel(dialogPlanchet)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(1050, 430, 20, 13))
        self.label_24.setFont(font)
        self.label_24.setScaledContents(True)
        self.label_25 = QLabel(dialogPlanchet)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(1050, 480, 20, 13))
        self.label_25.setFont(font)
        self.label_25.setScaledContents(True)
        self.label_26 = QLabel(dialogPlanchet)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(1050, 530, 20, 13))
        self.label_26.setFont(font)
        self.label_26.setScaledContents(True)
        self.label_27 = QLabel(dialogPlanchet)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(110, 560, 20, 13))
        self.label_27.setAlignment(Qt.AlignCenter)
        self.label_28 = QLabel(dialogPlanchet)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(250, 560, 20, 13))
        self.label_28.setScaledContents(True)
        self.label_28.setAlignment(Qt.AlignCenter)
        self.label_29 = QLabel(dialogPlanchet)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(390, 560, 20, 13))
        self.label_29.setScaledContents(True)
        self.label_29.setAlignment(Qt.AlignCenter)
        self.label_30 = QLabel(dialogPlanchet)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(530, 560, 20, 13))
        self.label_30.setScaledContents(True)
        self.label_30.setAlignment(Qt.AlignCenter)
        self.label_31 = QLabel(dialogPlanchet)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(670, 560, 20, 13))
        self.label_31.setScaledContents(True)
        self.label_31.setAlignment(Qt.AlignCenter)
        self.label_32 = QLabel(dialogPlanchet)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(810, 560, 20, 13))
        self.label_32.setScaledContents(True)
        self.label_32.setAlignment(Qt.AlignCenter)
        self.label_33 = QLabel(dialogPlanchet)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(960, 560, 20, 13))
        self.label_33.setScaledContents(True)
        self.label_33.setAlignment(Qt.AlignCenter)
        self.label_34 = QLabel(dialogPlanchet)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(390, 640, 20, 13))
        self.label_34.setScaledContents(True)
        self.label_34.setAlignment(Qt.AlignCenter)
        self.label_35 = QLabel(dialogPlanchet)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(530, 640, 20, 13))
        self.label_35.setScaledContents(True)
        self.label_35.setAlignment(Qt.AlignCenter)
        self.label_36 = QLabel(dialogPlanchet)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(670, 640, 20, 13))
        self.label_36.setScaledContents(True)
        self.label_36.setAlignment(Qt.AlignCenter)
        self.btnClose = QPushButton(dialogPlanchet)
        self.btnClose.setObjectName(u"btnClose")
        self.btnClose.setGeometry(QRect(980, 700, 80, 30))
        self.btnClose.setAutoDefault(False)
        self.btnSave = QPushButton(dialogPlanchet)
        self.btnSave.setObjectName(u"btnSave")
        self.btnSave.setEnabled(True)
        self.btnSave.setGeometry(QRect(890, 700, 80, 30))
        self.labelError = QLabel(dialogPlanchet)
        self.labelError.setObjectName(u"labelError")
        self.labelError.setGeometry(QRect(40, 660, 781, 61))
        self.labelError.setFont(font)
        self.labelError.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.labelError.setScaledContents(True)
        self.labelError.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.labelError.setWordWrap(True)
        self.comboTask1 = QComboBox(dialogPlanchet)
        self.comboTask1.setObjectName(u"comboTask1")
        self.comboTask1.setGeometry(QRect(710, 30, 351, 30))
        self.comboTask1.setEditable(False)
        self.comboTask1.setInsertPolicy(QComboBox.InsertAtTop)
        self.comboTask1.setMinimumContentsLength(0)
        self.label_37 = QLabel(dialogPlanchet)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(630, 30, 81, 30))
        self.label_37.setScaledContents(True)
        QWidget.setTabOrder(self.lineDescription, self.lineS1)
        QWidget.setTabOrder(self.lineS1, self.lineS2)
        QWidget.setTabOrder(self.lineS2, self.lineS3)
        QWidget.setTabOrder(self.lineS3, self.lineA1)
        QWidget.setTabOrder(self.lineA1, self.lineA2)
        QWidget.setTabOrder(self.lineA2, self.lineA3)
        QWidget.setTabOrder(self.lineA3, self.lineA4)
        QWidget.setTabOrder(self.lineA4, self.lineA5)
        QWidget.setTabOrder(self.lineA5, self.lineA6)
        QWidget.setTabOrder(self.lineA6, self.lineA7)
        QWidget.setTabOrder(self.lineA7, self.lineB1)
        QWidget.setTabOrder(self.lineB1, self.lineB2)
        QWidget.setTabOrder(self.lineB2, self.lineB3)
        QWidget.setTabOrder(self.lineB3, self.lineB4)
        QWidget.setTabOrder(self.lineB4, self.lineB5)
        QWidget.setTabOrder(self.lineB5, self.lineB6)
        QWidget.setTabOrder(self.lineB6, self.lineB7)
        QWidget.setTabOrder(self.lineB7, self.lineC1)
        QWidget.setTabOrder(self.lineC1, self.lineC2)
        QWidget.setTabOrder(self.lineC2, self.lineC3)
        QWidget.setTabOrder(self.lineC3, self.lineC4)
        QWidget.setTabOrder(self.lineC4, self.lineC5)
        QWidget.setTabOrder(self.lineC5, self.lineC6)
        QWidget.setTabOrder(self.lineC6, self.lineC7)
        QWidget.setTabOrder(self.lineC7, self.lineD1)
        QWidget.setTabOrder(self.lineD1, self.lineD2)
        QWidget.setTabOrder(self.lineD2, self.lineD3)
        QWidget.setTabOrder(self.lineD3, self.lineD4)
        QWidget.setTabOrder(self.lineD4, self.lineD5)
        QWidget.setTabOrder(self.lineD5, self.lineD6)
        QWidget.setTabOrder(self.lineD6, self.lineD7)
        QWidget.setTabOrder(self.lineD7, self.lineE1)
        QWidget.setTabOrder(self.lineE1, self.lineE2)
        QWidget.setTabOrder(self.lineE2, self.lineE3)
        QWidget.setTabOrder(self.lineE3, self.lineE4)
        QWidget.setTabOrder(self.lineE4, self.lineE5)
        QWidget.setTabOrder(self.lineE5, self.lineE6)
        QWidget.setTabOrder(self.lineE6, self.lineE7)
        QWidget.setTabOrder(self.lineE7, self.lineF1)
        QWidget.setTabOrder(self.lineF1, self.lineF2)
        QWidget.setTabOrder(self.lineF2, self.lineF3)
        QWidget.setTabOrder(self.lineF3, self.lineF4)
        QWidget.setTabOrder(self.lineF4, self.lineF5)
        QWidget.setTabOrder(self.lineF5, self.lineF6)
        QWidget.setTabOrder(self.lineF6, self.lineF7)
        QWidget.setTabOrder(self.lineF7, self.lineG1)
        QWidget.setTabOrder(self.lineG1, self.lineG2)
        QWidget.setTabOrder(self.lineG2, self.lineG3)
        QWidget.setTabOrder(self.lineG3, self.lineG4)
        QWidget.setTabOrder(self.lineG4, self.lineG5)
        QWidget.setTabOrder(self.lineG5, self.lineG6)
        QWidget.setTabOrder(self.lineG6, self.lineG7)
        QWidget.setTabOrder(self.lineG7, self.lineS4)
        QWidget.setTabOrder(self.lineS4, self.lineS5)
        QWidget.setTabOrder(self.lineS5, self.lineS6)
        QWidget.setTabOrder(self.lineS6, self.btnSave)
        QWidget.setTabOrder(self.btnSave, self.btnClose)
        QWidget.setTabOrder(self.btnClose, self.lineDate)

        self.retranslateUi(dialogPlanchet)

        self.btnClose.setDefault(False)
        self.btnSave.setDefault(True)
        self.comboTask1.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(dialogPlanchet)
    # setupUi

    def retranslateUi(self, dialogPlanchet):
        dialogPlanchet.setWindowTitle(QCoreApplication.translate("dialogPlanchet", u"New Planchet", None))
        self.lineS1.setText("")
        self.lineS2.setText("")
        self.lineS3.setText("")
        self.lineA3.setText("")
        self.lineA4.setText("")
        self.lineA2.setText("")
        self.lineA6.setText("")
        self.lineA7.setText("")
        self.lineA5.setText("")
        self.lineA1.setText("")
        self.lineB6.setText("")
        self.lineB2.setText("")
        self.lineB5.setText("")
        self.lineB3.setText("")
        self.lineB7.setText("")
        self.lineB1.setText("")
        self.lineB4.setText("")
        self.lineC6.setText("")
        self.lineC2.setText("")
        self.lineC5.setText("")
        self.lineC3.setText("")
        self.lineC7.setText("")
        self.lineC1.setText("")
        self.lineC4.setText("")
        self.lineD6.setText("")
        self.lineD2.setText("")
        self.lineD5.setText("")
        self.lineD3.setText("")
        self.lineD7.setText("")
        self.lineD1.setText("")
        self.lineD4.setText("")
        self.lineE6.setText("")
        self.lineE2.setText("")
        self.lineE5.setText("")
        self.lineE3.setText("")
        self.lineE7.setText("")
        self.lineE1.setText("")
        self.lineE4.setText("")
        self.lineF6.setText("")
        self.lineF2.setText("")
        self.lineF5.setText("")
        self.lineF3.setText("")
        self.lineF7.setText("")
        self.lineF1.setText("")
        self.lineF4.setText("")
        self.lineG6.setText("")
        self.lineG2.setText("")
        self.lineG5.setText("")
        self.lineG3.setText("")
        self.lineG7.setText("")
        self.lineG1.setText("")
        self.lineG4.setText("")
        self.lineS5.setText("")
        self.lineS6.setText("")
        self.lineS4.setText("")
        self.label_9.setText(QCoreApplication.translate("dialogPlanchet", u"Description", None))
        self.label_10.setText(QCoreApplication.translate("dialogPlanchet", u"Date Created", None))
        self.label.setText(QCoreApplication.translate("dialogPlanchet", u"S1", None))
        self.label_2.setText(QCoreApplication.translate("dialogPlanchet", u"S2", None))
        self.label_3.setText(QCoreApplication.translate("dialogPlanchet", u"S3", None))
        self.label_4.setText(QCoreApplication.translate("dialogPlanchet", u"A", None))
        self.label_5.setText(QCoreApplication.translate("dialogPlanchet", u"B", None))
        self.label_6.setText(QCoreApplication.translate("dialogPlanchet", u"C", None))
        self.label_7.setText(QCoreApplication.translate("dialogPlanchet", u"D", None))
        self.label_8.setText(QCoreApplication.translate("dialogPlanchet", u"E", None))
        self.label_11.setText(QCoreApplication.translate("dialogPlanchet", u"F", None))
        self.label_12.setText(QCoreApplication.translate("dialogPlanchet", u"G", None))
        self.label_13.setText(QCoreApplication.translate("dialogPlanchet", u"1", None))
        self.label_14.setText(QCoreApplication.translate("dialogPlanchet", u"2", None))
        self.label_15.setText(QCoreApplication.translate("dialogPlanchet", u"3", None))
        self.label_16.setText(QCoreApplication.translate("dialogPlanchet", u"4", None))
        self.label_17.setText(QCoreApplication.translate("dialogPlanchet", u"5", None))
        self.label_18.setText(QCoreApplication.translate("dialogPlanchet", u"6", None))
        self.label_19.setText(QCoreApplication.translate("dialogPlanchet", u"7", None))
        self.label_20.setText(QCoreApplication.translate("dialogPlanchet", u"A", None))
        self.label_21.setText(QCoreApplication.translate("dialogPlanchet", u"B", None))
        self.label_22.setText(QCoreApplication.translate("dialogPlanchet", u"C", None))
        self.label_23.setText(QCoreApplication.translate("dialogPlanchet", u"D", None))
        self.label_24.setText(QCoreApplication.translate("dialogPlanchet", u"E", None))
        self.label_25.setText(QCoreApplication.translate("dialogPlanchet", u"F", None))
        self.label_26.setText(QCoreApplication.translate("dialogPlanchet", u"G", None))
        self.label_27.setText(QCoreApplication.translate("dialogPlanchet", u"1", None))
        self.label_28.setText(QCoreApplication.translate("dialogPlanchet", u"2", None))
        self.label_29.setText(QCoreApplication.translate("dialogPlanchet", u"3", None))
        self.label_30.setText(QCoreApplication.translate("dialogPlanchet", u"4", None))
        self.label_31.setText(QCoreApplication.translate("dialogPlanchet", u"5", None))
        self.label_32.setText(QCoreApplication.translate("dialogPlanchet", u"6", None))
        self.label_33.setText(QCoreApplication.translate("dialogPlanchet", u"7", None))
        self.label_34.setText(QCoreApplication.translate("dialogPlanchet", u"S4", None))
        self.label_35.setText(QCoreApplication.translate("dialogPlanchet", u"S5", None))
        self.label_36.setText(QCoreApplication.translate("dialogPlanchet", u"S6", None))
        self.btnClose.setText(QCoreApplication.translate("dialogPlanchet", u"Close", None))
        self.btnSave.setText(QCoreApplication.translate("dialogPlanchet", u"Save", None))
        self.labelError.setText("")
        self.label_37.setText(QCoreApplication.translate("dialogPlanchet", u"Cycle", None))
    # retranslateUi

