# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'xymanualcontrol.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QFrame,
    QLabel, QPushButton, QSizePolicy, QToolButton,
    QWidget)
import main_rc

class Ui_dialogXYSetup(object):
    def setupUi(self, dialogXYSetup):
        if not dialogXYSetup.objectName():
            dialogXYSetup.setObjectName(u"dialogXYSetup")
        dialogXYSetup.setWindowModality(Qt.ApplicationModal)
        dialogXYSetup.resize(530, 330)
        dialogXYSetup.setMinimumSize(QSize(530, 330))
        dialogXYSetup.setMaximumSize(QSize(530, 330))
        icon = QIcon()
        icon.addFile(u":/main/iconGTRun.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        dialogXYSetup.setWindowIcon(icon)
        dialogXYSetup.setStyleSheet(u"font: 10pt \"Segoe UI\";")
        dialogXYSetup.setModal(True)
        self.lineYPosition = QLabel(dialogXYSetup)
        self.lineYPosition.setObjectName(u"lineYPosition")
        self.lineYPosition.setGeometry(QRect(160, 10, 121, 41))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.lineYPosition.setFont(font)
        self.lineYPosition.setToolTipDuration(5)
        self.lineYPosition.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 16pt \"Segoe UI\";")
        self.lineYPosition.setFrameShape(QFrame.Box)
        self.lineYPosition.setLineWidth(1)
        self.lblXpos = QLabel(dialogXYSetup)
        self.lblXpos.setObjectName(u"lblXpos")
        self.lblXpos.setGeometry(QRect(20, 60, 121, 20))
        self.lblXpos.setScaledContents(True)
        self.lblYpos = QLabel(dialogXYSetup)
        self.lblYpos.setObjectName(u"lblYpos")
        self.lblYpos.setGeometry(QRect(160, 60, 111, 20))
        self.lblYpos.setScaledContents(True)
        self.lineXPosition = QLabel(dialogXYSetup)
        self.lineXPosition.setObjectName(u"lineXPosition")
        self.lineXPosition.setGeometry(QRect(20, 10, 121, 41))
        self.lineXPosition.setFont(font)
        self.lineXPosition.setToolTipDuration(5)
        self.lineXPosition.setStyleSheet(u"font: 16pt \"Segoe UI\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lineXPosition.setFrameShape(QFrame.Box)
        self.lineXPosition.setLineWidth(1)
        self.btnUp = QToolButton(dialogXYSetup)
        self.btnUp.setObjectName(u"btnUp")
        self.btnUp.setGeometry(QRect(410, 50, 50, 50))
        icon1 = QIcon()
        icon1.addFile(u":/xy setup/arrorwe up.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon1.addFile(u":/xy setup/arrorw up.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.btnUp.setIcon(icon1)
        self.btnUp.setIconSize(QSize(30, 30))
        self.btnUp.setAutoRepeat(True)
        self.btnLeft = QToolButton(dialogXYSetup)
        self.btnLeft.setObjectName(u"btnLeft")
        self.btnLeft.setGeometry(QRect(360, 100, 50, 50))
        icon2 = QIcon()
        icon2.addFile(u":/xy setup/arrorwe left.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon2.addFile(u":/xy setup/arrorw left.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.btnLeft.setIcon(icon2)
        self.btnLeft.setIconSize(QSize(30, 30))
        self.btnLeft.setAutoRepeat(True)
        self.btnRight = QToolButton(dialogXYSetup)
        self.btnRight.setObjectName(u"btnRight")
        self.btnRight.setGeometry(QRect(460, 100, 50, 50))
        icon3 = QIcon()
        icon3.addFile(u":/xy setup/arrorwe right.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon3.addFile(u":/xy setup/arrorw right.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.btnRight.setIcon(icon3)
        self.btnRight.setIconSize(QSize(30, 30))
        self.btnRight.setCheckable(False)
        self.btnRight.setAutoRepeat(True)
        self.btnRight.setAutoRaise(False)
        self.btnDown = QToolButton(dialogXYSetup)
        self.btnDown.setObjectName(u"btnDown")
        self.btnDown.setGeometry(QRect(410, 150, 50, 50))
        icon4 = QIcon()
        icon4.addFile(u":/xy setup/arrorwe down.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon4.addFile(u":/xy setup/arrorw down.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.btnDown.setIcon(icon4)
        self.btnDown.setIconSize(QSize(30, 30))
        self.btnDown.setAutoRepeat(True)
        self.comboLocation1 = QComboBox(dialogXYSetup)
        self.comboLocation1.setObjectName(u"comboLocation1")
        self.comboLocation1.setEnabled(True)
        self.comboLocation1.setGeometry(QRect(20, 120, 161, 30))
        self.comboLocation1.setEditable(False)
        self.comboLocation1.setInsertPolicy(QComboBox.InsertAtBottom)
        self.label_2 = QLabel(dialogXYSetup)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 100, 151, 16))
        self.label_2.setScaledContents(True)
        self.btnGoto = QPushButton(dialogXYSetup)
        self.btnGoto.setObjectName(u"btnGoto")
        self.btnGoto.setGeometry(QRect(200, 120, 90, 30))
        self.btnSave = QPushButton(dialogXYSetup)
        self.btnSave.setObjectName(u"btnSave")
        self.btnSave.setGeometry(QRect(19, 170, 161, 30))
        self.btnSave.setToolTipDuration(-1)
        self.btnClose = QPushButton(dialogXYSetup)
        self.btnClose.setObjectName(u"btnClose")
        self.btnClose.setGeometry(QRect(400, 270, 90, 30))
        self.btnStop = QPushButton(dialogXYSetup)
        self.btnStop.setObjectName(u"btnStop")
        self.btnStop.setGeometry(QRect(290, 270, 90, 30))
        self.btnStop.setStyleSheet(u"color: rgb(255, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label = QLabel(dialogXYSetup)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 220, 261, 101))
        self.label.setStyleSheet(u"")
        self.label.setTextFormat(Qt.RichText)
        self.label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label_3 = QLabel(dialogXYSetup)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(360, 10, 151, 20))
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.btnGotoNext = QPushButton(dialogXYSetup)
        self.btnGotoNext.setObjectName(u"btnGotoNext")
        self.btnGotoNext.setGeometry(QRect(200, 170, 90, 30))
        self.bgdXgrn = QWidget(dialogXYSetup)
        self.bgdXgrn.setObjectName(u"bgdXgrn")
        self.bgdXgrn.setGeometry(QRect(20, 10, 121, 41))
        self.bgdXgrn.setStyleSheet(u"background-color: rgb(216, 255, 198);")
        self.bgdXred = QWidget(dialogXYSetup)
        self.bgdXred.setObjectName(u"bgdXred")
        self.bgdXred.setGeometry(QRect(20, 10, 121, 41))
        self.bgdXred.setStyleSheet(u"background-color: rgb(255, 164, 164);")
        self.bgdYred = QWidget(dialogXYSetup)
        self.bgdYred.setObjectName(u"bgdYred")
        self.bgdYred.setGeometry(QRect(160, 10, 121, 41))
        self.bgdYred.setStyleSheet(u"background-color: rgb(255, 164, 164);")
        self.bgdYgrn = QWidget(dialogXYSetup)
        self.bgdYgrn.setObjectName(u"bgdYgrn")
        self.bgdYgrn.setGeometry(QRect(160, 10, 121, 41))
        self.bgdYgrn.setStyleSheet(u"background-color: rgb(216, 255, 198);")
        self.bgdYgrn.raise_()
        self.bgdYred.raise_()
        self.bgdXgrn.raise_()
        self.bgdXred.raise_()
        self.lineYPosition.raise_()
        self.lblXpos.raise_()
        self.lblYpos.raise_()
        self.lineXPosition.raise_()
        self.btnUp.raise_()
        self.btnLeft.raise_()
        self.btnRight.raise_()
        self.btnDown.raise_()
        self.comboLocation1.raise_()
        self.label_2.raise_()
        self.btnGoto.raise_()
        self.btnSave.raise_()
        self.btnClose.raise_()
        self.btnStop.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.btnGotoNext.raise_()

        self.retranslateUi(dialogXYSetup)

        self.comboLocation1.setCurrentIndex(-1)


        QMetaObject.connectSlotsByName(dialogXYSetup)
    # setupUi

    def retranslateUi(self, dialogXYSetup):
        dialogXYSetup.setWindowTitle(QCoreApplication.translate("dialogXYSetup", u"Calibrate X-Y Control", None))
#if QT_CONFIG(tooltip)
        self.lineYPosition.setToolTip(QCoreApplication.translate("dialogXYSetup", u"X position GREEN = on location RED = moving", None))
#endif // QT_CONFIG(tooltip)
        self.lineYPosition.setText(QCoreApplication.translate("dialogXYSetup", u"0.0", None))
        self.lblXpos.setText(QCoreApplication.translate("dialogXYSetup", u"X Position", None))
        self.lblYpos.setText(QCoreApplication.translate("dialogXYSetup", u"Y Position", None))
#if QT_CONFIG(tooltip)
        self.lineXPosition.setToolTip(QCoreApplication.translate("dialogXYSetup", u"X position GREEN = on location RED = moving", None))
#endif // QT_CONFIG(tooltip)
        self.lineXPosition.setText(QCoreApplication.translate("dialogXYSetup", u"0.0", None))
#if QT_CONFIG(tooltip)
        self.btnUp.setToolTip(QCoreApplication.translate("dialogXYSetup", u"Move Up", None))
#endif // QT_CONFIG(tooltip)
        self.btnUp.setText("")
#if QT_CONFIG(tooltip)
        self.btnLeft.setToolTip(QCoreApplication.translate("dialogXYSetup", u"Move Left", None))
#endif // QT_CONFIG(tooltip)
        self.btnLeft.setText("")
#if QT_CONFIG(tooltip)
        self.btnRight.setToolTip(QCoreApplication.translate("dialogXYSetup", u"Move Right", None))
#endif // QT_CONFIG(tooltip)
        self.btnRight.setText("")
#if QT_CONFIG(tooltip)
        self.btnDown.setToolTip(QCoreApplication.translate("dialogXYSetup", u"Move Down", None))
#endif // QT_CONFIG(tooltip)
        self.btnDown.setText("")
        self.comboLocation1.setCurrentText("")
        self.label_2.setText(QCoreApplication.translate("dialogXYSetup", u"Location", None))
#if QT_CONFIG(tooltip)
        self.btnGoto.setToolTip(QCoreApplication.translate("dialogXYSetup", u"Goto the location specified", None))
#endif // QT_CONFIG(tooltip)
        self.btnGoto.setText(QCoreApplication.translate("dialogXYSetup", u"Goto", None))
#if QT_CONFIG(tooltip)
        self.btnSave.setToolTip(QCoreApplication.translate("dialogXYSetup", u"Saves the current X and Y position to the location shown", u"Saves the current X and Y position to the location shown"))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.btnSave.setStatusTip(QCoreApplication.translate("dialogXYSetup", u"Saves the current X and Y position to the location shown", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.btnSave.setWhatsThis(QCoreApplication.translate("dialogXYSetup", u"Saves the current X and Y position to the location shown", None))
#endif // QT_CONFIG(whatsthis)
        self.btnSave.setText(QCoreApplication.translate("dialogXYSetup", u"Save Current", None))
        self.btnClose.setText(QCoreApplication.translate("dialogXYSetup", u"Close", None))
#if QT_CONFIG(tooltip)
        self.btnStop.setToolTip(QCoreApplication.translate("dialogXYSetup", u"Stop the stage moving", None))
#endif // QT_CONFIG(tooltip)
        self.btnStop.setText(QCoreApplication.translate("dialogXYSetup", u"STOP", None))
        self.label.setText(QCoreApplication.translate("dialogXYSetup", u"<html><head/><body><p><span style=\" font-weight:600;\">Warning</span>: <span style=\" color:#ce3a08;\">Please ensure that the X-Y table has finished moving </span><span style=\" color:#328812;\">(positions are </span><span style=\" font-weight:600; color:#328812;\">green</span><span style=\" color:#328812;\">) </span><span style=\" color:#ce3a08;\">before pressing </span><span style=\" font-weight:600;\">Save Current</span></p></body></html>", None))
        self.label_3.setText(QCoreApplication.translate("dialogXYSetup", u"Manual Control", None))
        self.btnGotoNext.setText(QCoreApplication.translate("dialogXYSetup", u"Goto Next", None))
    # retranslateUi

