# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.7.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QFrame, QHeaderView,
    QLCDNumber, QLabel, QListWidget, QListWidgetItem,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QTableWidget, QTableWidgetItem, QToolButton,
    QWidget)
import main_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1800, 1000)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1800, 1000))
        MainWindow.setMaximumSize(QSize(1800, 1000))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u":/main/iconPyMSRun.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon.addFile(u":/main/iconPyMSRun.svg", QSize(), QIcon.Mode.Disabled, QIcon.State.Off)
        icon.addFile(u":/main/iconPyMSRun.svg", QSize(), QIcon.Mode.Selected, QIcon.State.Off)
        icon.addFile(u":/main/iconPyMSRun.svg", QSize(), QIcon.Mode.Selected, QIcon.State.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"background-color: rgb(235, 235, 235);\n"
"border-color: rgb(255, 255, 255);\n"
"font: 10pt \"Segoe UI\";\n"
"")
        MainWindow.setIconSize(QSize(32, 32))
        MainWindow.setAnimated(True)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(10)
        self.actionExit.setFont(font1)
        self.actionStartNewBatch = QAction(MainWindow)
        self.actionStartNewBatch.setObjectName(u"actionStartNewBatch")
        self.actionStartNewBatch.setFont(font1)
        self.actionXYOpenStatusPage = QAction(MainWindow)
        self.actionXYOpenStatusPage.setObjectName(u"actionXYOpenStatusPage")
        self.actionXYOpenStatusPage.setFont(font1)
        self.actionXYOpenLogPage = QAction(MainWindow)
        self.actionXYOpenLogPage.setObjectName(u"actionXYOpenLogPage")
        self.actionXYOpenLogPage.setFont(font1)
        self.actionValveOpenStatusPage = QAction(MainWindow)
        self.actionValveOpenStatusPage.setObjectName(u"actionValveOpenStatusPage")
        self.actionValveOpenStatusPage.setFont(font1)
        self.actionValveOpenLogPage = QAction(MainWindow)
        self.actionValveOpenLogPage.setObjectName(u"actionValveOpenLogPage")
        self.actionValveOpenLogPage.setFont(font1)
        self.actionManualControl = QAction(MainWindow)
        self.actionManualControl.setObjectName(u"actionManualControl")
        self.actionManualControl.setFont(font1)
        self.actionViewPyMSLog = QAction(MainWindow)
        self.actionViewPyMSLog.setObjectName(u"actionViewPyMSLog")
        self.actionViewPyMSLog.setFont(font1)
        self.actionAboutPyMS = QAction(MainWindow)
        self.actionAboutPyMS.setObjectName(u"actionAboutPyMS")
        self.actionAboutPyMS.setFont(font1)
        self.actionViewPyMSSettings = QAction(MainWindow)
        self.actionViewPyMSSettings.setObjectName(u"actionViewPyMSSettings")
        self.actionViewPyMSSettings.setFont(font1)
        self.actionPumpOpenStatusPage = QAction(MainWindow)
        self.actionPumpOpenStatusPage.setObjectName(u"actionPumpOpenStatusPage")
        self.actionPumpOpenLogPage = QAction(MainWindow)
        self.actionPumpOpenLogPage.setObjectName(u"actionPumpOpenLogPage")
        self.actionStartMIDScan = QAction(MainWindow)
        self.actionStartMIDScan.setObjectName(u"actionStartMIDScan")
        self.actionStartProfileScan = QAction(MainWindow)
        self.actionStartProfileScan.setObjectName(u"actionStartProfileScan")
        self.actionStopScan = QAction(MainWindow)
        self.actionStopScan.setObjectName(u"actionStopScan")
        self.actionLaserOpenStatusPage = QAction(MainWindow)
        self.actionLaserOpenStatusPage.setObjectName(u"actionLaserOpenStatusPage")
        self.actionLaserOpenLogPage = QAction(MainWindow)
        self.actionLaserOpenLogPage.setObjectName(u"actionLaserOpenLogPage")
        self.actionCO2LaserOn = QAction(MainWindow)
        self.actionCO2LaserOn.setObjectName(u"actionCO2LaserOn")
        self.actionReboot_XY = QAction(MainWindow)
        self.actionReboot_XY.setObjectName(u"actionReboot_XY")
        self.actionReboot_Laser = QAction(MainWindow)
        self.actionReboot_Laser.setObjectName(u"actionReboot_Laser")
        self.actionReboot_Valve = QAction(MainWindow)
        self.actionReboot_Valve.setObjectName(u"actionReboot_Valve")
        self.actionReboot_Pump = QAction(MainWindow)
        self.actionReboot_Pump.setObjectName(u"actionReboot_Pump")
        self.actionNCCViewer = QAction(MainWindow)
        self.actionNCCViewer.setObjectName(u"actionNCCViewer")
        self.actionHelp = QAction(MainWindow)
        self.actionHelp.setObjectName(u"actionHelp")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frmHeLine = QFrame(self.centralwidget)
        self.frmHeLine.setObjectName(u"frmHeLine")
        self.frmHeLine.setEnabled(True)
        self.frmHeLine.setGeometry(QRect(330, 100, 950, 852))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frmHeLine.sizePolicy().hasHeightForWidth())
        self.frmHeLine.setSizePolicy(sizePolicy1)
        self.frmHeLine.setMinimumSize(QSize(949, 852))
        self.frmHeLine.setMaximumSize(QSize(950, 852))
#if QT_CONFIG(tooltip)
        self.frmHeLine.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.frmHeLine.setStyleSheet(u"background-color: rgba(255, 255, 255,);\n"
"image: \"\";")
        self.frmHeLine.setFrameShape(QFrame.Box)
        self.frmHeLine.setFrameShadow(QFrame.Plain)
        self.frmHeLine.setLineWidth(1)
        self.frmHeLine.setMidLineWidth(1)
        self.imgLaser = QFrame(self.frmHeLine)
        self.imgLaser.setObjectName(u"imgLaser")
        self.imgLaser.setEnabled(False)
        self.imgLaser.setGeometry(QRect(72, 361, 110, 116))
        self.imgLaser.setStyleSheet(u"image: url(:/main/laser.png);")
        self.imgLaser.setFrameShape(QFrame.NoFrame)
        self.imgLaser.setFrameShadow(QFrame.Plain)
        self.wValve1 = QWidget(self.frmHeLine)
        self.wValve1.setObjectName(u"wValve1")
        self.wValve1.setGeometry(QRect(269, 261, 35, 35))
        self.wValve1.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.tbValve1 = QPushButton(self.frmHeLine)
        self.tbValve1.setObjectName(u"tbValve1")
        self.tbValve1.setGeometry(QRect(271, 263, 36, 31))
        self.tbValve1.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.wValve2 = QWidget(self.frmHeLine)
        self.wValve2.setObjectName(u"wValve2")
        self.wValve2.setGeometry(QRect(337, 260, 36, 36))
        self.wValve2.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.tbValve2 = QPushButton(self.frmHeLine)
        self.tbValve2.setObjectName(u"tbValve2")
        self.tbValve2.setGeometry(QRect(338, 261, 36, 35))
        self.tbValve2.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.wValve6 = QWidget(self.frmHeLine)
        self.wValve6.setObjectName(u"wValve6")
        self.wValve6.setGeometry(QRect(336, 116, 36, 36))
        self.wValve6.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.wValve7 = QWidget(self.frmHeLine)
        self.wValve7.setObjectName(u"wValve7")
        self.wValve7.setGeometry(QRect(482, 116, 36, 36))
        self.wValve7.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.wValve3 = QWidget(self.frmHeLine)
        self.wValve3.setObjectName(u"wValve3")
        self.wValve3.setGeometry(QRect(482, 260, 36, 36))
        self.wValve3.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.wValve4 = QWidget(self.frmHeLine)
        self.wValve4.setObjectName(u"wValve4")
        self.wValve4.setGeometry(QRect(551, 260, 36, 36))
        self.wValve4.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.wValve10 = QWidget(self.frmHeLine)
        self.wValve10.setObjectName(u"wValve10")
        self.wValve10.setGeometry(QRect(336, 402, 36, 36))
        self.wValve10.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.wValve11 = QWidget(self.frmHeLine)
        self.wValve11.setObjectName(u"wValve11")
        self.wValve11.setGeometry(QRect(482, 402, 36, 36))
        self.wValve11.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.wValve12 = QWidget(self.frmHeLine)
        self.wValve12.setObjectName(u"wValve12")
        self.wValve12.setGeometry(QRect(315, 694, 36, 36))
        self.wValve12.setStyleSheet(u"image: url(:/valves/valve green horizontal.png);")
        self.wValve8 = QWidget(self.frmHeLine)
        self.wValve8.setObjectName(u"wValve8")
        self.wValve8.setGeometry(QRect(408, 188, 36, 36))
        self.wValve8.setStyleSheet(u"image: url(:/valves/valve green vertical.png);")
        self.wValve5 = QWidget(self.frmHeLine)
        self.wValve5.setObjectName(u"wValve5")
        self.wValve5.setGeometry(QRect(407, 521, 36, 36))
        self.wValve5.setStyleSheet(u"image: url(:/valves/valve green vertical.png);")
        self.wValve13 = QWidget(self.frmHeLine)
        self.wValve13.setObjectName(u"wValve13")
        self.wValve13.setGeometry(QRect(480, 522, 36, 36))
        self.wValve13.setStyleSheet(u"image: url(:/valves/valve green vertical.png);")
        self.tbValve6 = QPushButton(self.frmHeLine)
        self.tbValve6.setObjectName(u"tbValve6")
        self.tbValve6.setGeometry(QRect(338, 115, 36, 36))
        self.tbValve6.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.tbValve7 = QPushButton(self.frmHeLine)
        self.tbValve7.setObjectName(u"tbValve7")
        self.tbValve7.setGeometry(QRect(484, 116, 36, 36))
        self.tbValve7.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.tbValve8 = QPushButton(self.frmHeLine)
        self.tbValve8.setObjectName(u"tbValve8")
        self.tbValve8.setGeometry(QRect(409, 189, 36, 36))
        self.tbValve8.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.tbValve3 = QPushButton(self.frmHeLine)
        self.tbValve3.setObjectName(u"tbValve3")
        self.tbValve3.setGeometry(QRect(485, 260, 36, 36))
        self.tbValve3.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.tbValve4 = QPushButton(self.frmHeLine)
        self.tbValve4.setObjectName(u"tbValve4")
        self.tbValve4.setGeometry(QRect(554, 262, 36, 36))
        self.tbValve4.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.tbValve10 = QPushButton(self.frmHeLine)
        self.tbValve10.setObjectName(u"tbValve10")
        self.tbValve10.setGeometry(QRect(339, 401, 36, 36))
        self.tbValve10.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.tbValve11 = QPushButton(self.frmHeLine)
        self.tbValve11.setObjectName(u"tbValve11")
        self.tbValve11.setGeometry(QRect(484, 401, 36, 36))
        self.tbValve11.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.tbValve5 = QPushButton(self.frmHeLine)
        self.tbValve5.setObjectName(u"tbValve5")
        self.tbValve5.setGeometry(QRect(408, 518, 36, 36))
        self.tbValve5.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.tbValve13 = QPushButton(self.frmHeLine)
        self.tbValve13.setObjectName(u"tbValve13")
        self.tbValve13.setGeometry(QRect(481, 519, 36, 35))
        self.tbValve13.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.tbValve12 = QPushButton(self.frmHeLine)
        self.tbValve12.setObjectName(u"tbValve12")
        self.tbValve12.setGeometry(QRect(316, 692, 36, 36))
        self.tbValve12.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);")
        self.lblMS = QLabel(self.frmHeLine)
        self.lblMS.setObjectName(u"lblMS")
        self.lblMS.setGeometry(QRect(394, 3, 321, 29))
        self.lblMS.setFont(font)
        self.lblMS.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.imgQMS = QFrame(self.frmHeLine)
        self.imgQMS.setObjectName(u"imgQMS")
        self.imgQMS.setGeometry(QRect(516, 24, 79, 111))
        self.imgQMS.setStyleSheet(u"image: url(:/main/QMS.png);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.imgQMS.setFrameShape(QFrame.StyledPanel)
        self.imgQMS.setFrameShadow(QFrame.Raised)
        self.btnHidenMID = QToolButton(self.frmHeLine)
        self.btnHidenMID.setObjectName(u"btnHidenMID")
        self.btnHidenMID.setGeometry(QRect(370, 30, 50, 50))
        self.btnHidenMID.setStyleSheet(u"")
        icon1 = QIcon()
        icon1.addFile(u":/main/hiden-mid.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon1.addFile(u":/main/hiden-disabled.png", QSize(), QIcon.Mode.Disabled, QIcon.State.Off)
        icon1.addFile(u":/main/hiden-disabled.png", QSize(), QIcon.Mode.Disabled, QIcon.State.On)
        self.btnHidenMID.setIcon(icon1)
        self.btnHidenMID.setIconSize(QSize(46, 46))
        self.btnHidenMID.setAutoRaise(False)
        self.btnHidenProfile = QToolButton(self.frmHeLine)
        self.btnHidenProfile.setObjectName(u"btnHidenProfile")
        self.btnHidenProfile.setGeometry(QRect(420, 30, 50, 50))
        icon2 = QIcon()
        icon2.addFile(u":/main/hiden-profile.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon2.addFile(u":/main/hiden-disabled.png", QSize(), QIcon.Mode.Disabled, QIcon.State.Off)
        icon2.addFile(u":/main/hiden-disabled.png", QSize(), QIcon.Mode.Disabled, QIcon.State.On)
        self.btnHidenProfile.setIcon(icon2)
        self.btnHidenProfile.setIconSize(QSize(46, 46))
        self.btnHidenStop = QToolButton(self.frmHeLine)
        self.btnHidenStop.setObjectName(u"btnHidenStop")
        self.btnHidenStop.setGeometry(QRect(470, 30, 50, 50))
        icon3 = QIcon()
        icon3.addFile(u":/main/hiden-stop.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon3.addFile(u":/main/hiden-disabled.png", QSize(), QIcon.Mode.Disabled, QIcon.State.Off)
        icon3.addFile(u":/main/hiden-disabled.png", QSize(), QIcon.Mode.Disabled, QIcon.State.On)
        self.btnHidenStop.setIcon(icon3)
        self.btnHidenStop.setIconSize(QSize(46, 46))
        self.lblLaserPower = QLabel(self.frmHeLine)
        self.lblLaserPower.setObjectName(u"lblLaserPower")
        self.lblLaserPower.setGeometry(QRect(86, 563, 89, 21))
        self.lblLaserPower.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(76, 76, 76);")
        self.lblLaserPower.setFrameShape(QFrame.Panel)
        self.lblLaserPower.setFrameShadow(QFrame.Sunken)
        self.lblLaserPower.setLineWidth(1)
        self.lblLaserPower.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.lblLaserPower.setTextInteractionFlags(Qt.TextSelectableByMouse)
        self.lcdElapsedTime = QLCDNumber(self.centralwidget)
        self.lcdElapsedTime.setObjectName(u"lcdElapsedTime")
        self.lcdElapsedTime.setGeometry(QRect(10, 5, 131, 41))
        self.lcdElapsedTime.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"image: \"\";")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 45, 135, 21))
        self.label.setStyleSheet(u"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        self.label.setScaledContents(True)
        self.label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 340, 251, 21))
        self.label_2.setStyleSheet(u"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        self.label_2.setScaledContents(True)
        self.lblStatus = QLabel(self.centralwidget)
        self.lblStatus.setObjectName(u"lblStatus")
        self.lblStatus.setGeometry(QRect(330, 75, 571, 21))
        self.lblStatus.setStyleSheet(u"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        self.lblStatus.setScaledContents(True)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 76, 191, 20))
        self.label_4.setStyleSheet(u"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        self.label_4.setScaledContents(True)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 135, 171, 21))
        self.label_5.setStyleSheet(u"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        self.label_5.setScaledContents(True)
        self.tbStop = QToolButton(self.centralwidget)
        self.tbStop.setObjectName(u"tbStop")
        self.tbStop.setGeometry(QRect(169, 820, 134, 134))
        self.tbStop.setAcceptDrops(True)
#if QT_CONFIG(tooltip)
        self.tbStop.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.tbStop.setStyleSheet(u"border-color: rgb(255, 255, 255);\n"
"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        icon4 = QIcon()
        icon4.addFile(u":/main/stop_up.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon4.addFile(u":/main/stop_down.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.tbStop.setIcon(icon4)
        self.tbStop.setIconSize(QSize(154, 150))
        self.tbStop.setCheckable(True)
        self.tbStop.setPopupMode(QToolButton.DelayedPopup)
        self.tbStop.setAutoRaise(True)
        self.tbStop.setArrowType(Qt.NoArrow)
        self.tbRun = QToolButton(self.centralwidget)
        self.tbRun.setObjectName(u"tbRun")
        self.tbRun.setGeometry(QRect(10, 810, 84, 44))
#if QT_CONFIG(tooltip)
        self.tbRun.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.tbRun.setStyleSheet(u"image: \"\";")
        icon5 = QIcon()
        icon5.addFile(u":/main/run.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon5.addFile(u":/main/pause.png", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.tbRun.setIcon(icon5)
        self.tbRun.setIconSize(QSize(84, 44))
        self.tbRun.setCheckable(True)
        self.listCommands = QListWidget(self.centralwidget)
        self.listCommands.setObjectName(u"listCommands")
        self.listCommands.setGeometry(QRect(10, 370, 301, 181))
        self.listCommands.setFont(font)
        self.listCommands.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(61, 61, 61);\n"
"alternate-background-color: rgb(225, 245, 255);\n"
"image: \"\";")
        self.listCommands.setMidLineWidth(1)
        self.listCommands.setAlternatingRowColors(True)
        self.listCommands.setSelectionMode(QAbstractItemView.NoSelection)
        self.lblIonPump = QLabel(self.centralwidget)
        self.lblIonPump.setObjectName(u"lblIonPump")
        self.lblIonPump.setGeometry(QRect(910, 46, 121, 21))
        self.lblIonPump.setStyleSheet(u"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        self.lblIonPump.setScaledContents(True)
        self.lblTurboPump = QLabel(self.centralwidget)
        self.lblTurboPump.setObjectName(u"lblTurboPump")
        self.lblTurboPump.setGeometry(QRect(1050, 46, 121, 21))
        self.lblTurboPump.setStyleSheet(u"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        self.lblTurboPump.setScaledContents(True)
        self.lblTankPump = QLabel(self.centralwidget)
        self.lblTankPump.setObjectName(u"lblTankPump")
        self.lblTankPump.setGeometry(QRect(1190, 46, 121, 21))
        self.lblTankPump.setStyleSheet(u"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        self.lblTankPump.setScaledContents(True)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 560, 251, 21))
        self.label_8.setStyleSheet(u"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        self.label_8.setScaledContents(True)
        self.listBatch = QListWidget(self.centralwidget)
        self.listBatch.setObjectName(u"listBatch")
        self.listBatch.setGeometry(QRect(10, 590, 301, 211))
        self.listBatch.setFont(font)
        self.listBatch.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(61, 61, 61);\n"
"alternate-background-color: rgb(225, 245, 255);\n"
"image: \"\";")
        self.listBatch.setMidLineWidth(1)
        self.listBatch.setAlternatingRowColors(True)
        self.listBatch.setSelectionMode(QAbstractItemView.NoSelection)
        self.listBatch.setModelColumn(0)
        self.linePlanchet = QLabel(self.centralwidget)
        self.linePlanchet.setObjectName(u"linePlanchet")
        self.linePlanchet.setGeometry(QRect(10, 100, 301, 30))
        self.linePlanchet.setFont(font)
        self.linePlanchet.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"image: \"\";")
        self.linePlanchet.setFrameShape(QFrame.Box)
        self.linePlanchet.setLineWidth(1)
        self.lineLocation = QLabel(self.centralwidget)
        self.lineLocation.setObjectName(u"lineLocation")
        self.lineLocation.setGeometry(QRect(10, 160, 301, 30))
        self.lineLocation.setFont(font)
        self.lineLocation.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"image: \"\";")
        self.lineLocation.setFrameShape(QFrame.Box)
        self.lineIonPump = QLabel(self.centralwidget)
        self.lineIonPump.setObjectName(u"lineIonPump")
        self.lineIonPump.setGeometry(QRect(910, 5, 121, 41))
        font2 = QFont()
        font2.setFamilies([u"Segoe UI"])
        font2.setPointSize(14)
        font2.setBold(False)
        font2.setItalic(False)
        self.lineIonPump.setFont(font2)
        self.lineIonPump.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Segoe UI\";\n"
"image: \"\";")
        self.lineIonPump.setFrameShape(QFrame.Box)
        self.lineIonPump.setLineWidth(1)
        self.lineIonPump.setScaledContents(True)
        self.lineTurboPump = QLabel(self.centralwidget)
        self.lineTurboPump.setObjectName(u"lineTurboPump")
        self.lineTurboPump.setGeometry(QRect(1050, 5, 121, 41))
        self.lineTurboPump.setFont(font2)
        self.lineTurboPump.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Segoe UI\";\n"
"image: \"\";")
        self.lineTurboPump.setFrameShape(QFrame.Box)
        self.lineTurboPump.setLineWidth(1)
        self.lineTurboPump.setScaledContents(True)
        self.lineScrollPump = QLabel(self.centralwidget)
        self.lineScrollPump.setObjectName(u"lineScrollPump")
        self.lineScrollPump.setGeometry(QRect(1190, 5, 121, 41))
        self.lineScrollPump.setFont(font2)
        self.lineScrollPump.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Segoe UI\";\n"
"image: \"\";")
        self.lineScrollPump.setFrameShape(QFrame.Box)
        self.lineScrollPump.setLineWidth(1)
        self.lineScrollPump.setScaledContents(True)
        self.lineXPosition = QLabel(self.centralwidget)
        self.lineXPosition.setObjectName(u"lineXPosition")
        self.lineXPosition.setGeometry(QRect(600, 5, 111, 41))
        self.lineXPosition.setFont(font2)
        self.lineXPosition.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Segoe UI\";\n"
"image: \"\";")
        self.lineXPosition.setFrameShape(QFrame.Box)
        self.lineXPosition.setLineWidth(1)
        self.lineXPosition.setScaledContents(True)
        self.lineYPosition = QLabel(self.centralwidget)
        self.lineYPosition.setObjectName(u"lineYPosition")
        self.lineYPosition.setGeometry(QRect(730, 5, 111, 41))
        self.lineYPosition.setFont(font2)
        self.lineYPosition.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Segoe UI\";\n"
"image: \"\";")
        self.lineYPosition.setFrameShape(QFrame.Box)
        self.lineYPosition.setLineWidth(1)
        self.lineYPosition.setScaledContents(True)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(600, 46, 111, 21))
        self.label_9.setStyleSheet(u"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        self.label_9.setScaledContents(True)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(730, 46, 111, 21))
        self.label_10.setStyleSheet(u"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        self.label_10.setScaledContents(True)
        self.frmImage = QFrame(self.centralwidget)
        self.frmImage.setObjectName(u"frmImage")
        self.frmImage.setGeometry(QRect(331, 82, 950, 880))
        self.frmImage.setStyleSheet(u"image: url(:/main/main.png);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.frmImage.setFrameShape(QFrame.StyledPanel)
        self.frmImage.setFrameShadow(QFrame.Raised)
        self.lblCurrent = QLabel(self.centralwidget)
        self.lblCurrent.setObjectName(u"lblCurrent")
        self.lblCurrent.setGeometry(QRect(10, 220, 301, 101))
        self.lblCurrent.setStyleSheet(u"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        self.lblCurrent.setScaledContents(True)
        self.lblCurrent.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.lblCurrent.setWordWrap(True)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(1290, 75, 151, 21))
        self.label_11.setStyleSheet(u"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        self.label_11.setScaledContents(True)
        self.lblAalarm = QLabel(self.centralwidget)
        self.lblAalarm.setObjectName(u"lblAalarm")
        self.lblAalarm.setGeometry(QRect(610, 850, 650, 90))
        font3 = QFont()
        font3.setFamilies([u"Segoe UI"])
        font3.setPointSize(8)
        font3.setWeight(QFont.DemiBold)
        font3.setItalic(False)
        self.lblAalarm.setFont(font3)
        self.lblAalarm.setStyleSheet(u"background-color: rgba(255, 255, 255, 0);\n"
"font: 600 8pt \"Segoe UI\";\n"
"color: rgb(255, 0, 0);\n"
"")
        self.lblAalarm.setScaledContents(True)
        self.lblAalarm.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.lblAalarm.setWordWrap(True)
        self.lblAalarm.setTextInteractionFlags(Qt.NoTextInteraction)
        self.lblFinishTime = QLabel(self.centralwidget)
        self.lblFinishTime.setObjectName(u"lblFinishTime")
        self.lblFinishTime.setGeometry(QRect(150, 10, 431, 41))
        self.lblFinishTime.setStyleSheet(u"font: 12pt \"Segoe UI\";\n"
"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        self.lblFinishTime.setScaledContents(True)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 200, 171, 21))
        self.label_13.setStyleSheet(u"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        self.label_13.setScaledContents(True)
        self.btnNCCViewer = QPushButton(self.centralwidget)
        self.btnNCCViewer.setObjectName(u"btnNCCViewer")
        self.btnNCCViewer.setGeometry(QRect(1697, 66, 91, 31))
#if QT_CONFIG(tooltip)
        self.btnNCCViewer.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.btnNCCViewer.setStyleSheet(u"font: 700 10pt \"Segoe UI\";\n"
"image: \"\";")
        self.btnNCCViewer.setIconSize(QSize(33, 32))
        self.frameResults = QFrame(self.centralwidget)
        self.frameResults.setObjectName(u"frameResults")
        self.frameResults.setGeometry(QRect(1290, 100, 504, 854))
        self.frameResults.setStyleSheet(u"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        self.frameResults.setFrameShape(QFrame.Box)
        self.frameResults.setFrameShadow(QFrame.Plain)
        self.tableResults = QTableWidget(self.frameResults)
        if (self.tableResults.columnCount() < 4):
            self.tableResults.setColumnCount(4)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.tableResults.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.tableResults.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.tableResults.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        __qtablewidgetitem3.setTextAlignment(Qt.AlignLeading|Qt.AlignVCenter);
        self.tableResults.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        self.tableResults.setObjectName(u"tableResults")
        self.tableResults.setGeometry(QRect(1, 1, 500, 851))
        self.tableResults.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(61, 61, 61);\n"
"alternate-background-color: rgb(225, 245, 255);\n"
"image: \"\";")
        self.tableResults.setLineWidth(1)
        self.tableResults.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.tableResults.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.tableResults.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableResults.setDragDropOverwriteMode(False)
        self.tableResults.setAlternatingRowColors(True)
        self.tableResults.setSelectionMode(QAbstractItemView.NoSelection)
        self.tableResults.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableResults.setTextElideMode(Qt.ElideLeft)
        self.tableResults.setWordWrap(False)
        self.tableResults.horizontalHeader().setHighlightSections(False)
        self.tableResults.horizontalHeader().setStretchLastSection(False)
        self.tableResults.verticalHeader().setVisible(False)
        self.tableResults.verticalHeader().setHighlightSections(False)
        self.lineN2Pressure = QLabel(self.centralwidget)
        self.lineN2Pressure.setObjectName(u"lineN2Pressure")
        self.lineN2Pressure.setGeometry(QRect(1330, 5, 121, 41))
        self.lineN2Pressure.setFont(font2)
        self.lineN2Pressure.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font: 14pt \"Segoe UI\";\n"
"image: \"\";")
        self.lineN2Pressure.setFrameShape(QFrame.Box)
        self.lineN2Pressure.setLineWidth(1)
        self.lineN2Pressure.setScaledContents(True)
        self.lblN2Pump = QLabel(self.centralwidget)
        self.lblN2Pump.setObjectName(u"lblN2Pump")
        self.lblN2Pump.setGeometry(QRect(1330, 46, 121, 21))
        self.lblN2Pump.setStyleSheet(u"background-color: rgba(235, 235, 235, 0);\n"
"image: \"\";")
        self.lblN2Pump.setScaledContents(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.frmImage.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.frmHeLine.raise_()
        self.lcdElapsedTime.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lblStatus.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.tbStop.raise_()
        self.tbRun.raise_()
        self.listCommands.raise_()
        self.lblIonPump.raise_()
        self.lblTurboPump.raise_()
        self.lblTankPump.raise_()
        self.label_8.raise_()
        self.listBatch.raise_()
        self.linePlanchet.raise_()
        self.lineLocation.raise_()
        self.lineIonPump.raise_()
        self.lineTurboPump.raise_()
        self.lineScrollPump.raise_()
        self.lineXPosition.raise_()
        self.lineYPosition.raise_()
        self.lblCurrent.raise_()
        self.label_11.raise_()
        self.lblAalarm.raise_()
        self.lblFinishTime.raise_()
        self.label_13.raise_()
        self.btnNCCViewer.raise_()
        self.frameResults.raise_()
        self.lineN2Pressure.raise_()
        self.lblN2Pump.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1800, 24))
        self.menubar.setNativeMenuBar(True)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuBatch = QMenu(self.menubar)
        self.menuBatch.setObjectName(u"menuBatch")
        self.menuXYController = QMenu(self.menubar)
        self.menuXYController.setObjectName(u"menuXYController")
        self.menuValveController = QMenu(self.menubar)
        self.menuValveController.setObjectName(u"menuValveController")
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuPump_Reader = QMenu(self.menubar)
        self.menuPump_Reader.setObjectName(u"menuPump_Reader")
        self.menuMass_Spectrometer = QMenu(self.menubar)
        self.menuMass_Spectrometer.setObjectName(u"menuMass_Spectrometer")
        self.menuMass_Spectrometer.setEnabled(True)
        self.menuLaser_Controller = QMenu(self.menubar)
        self.menuLaser_Controller.setObjectName(u"menuLaser_Controller")
        MainWindow.setMenuBar(self.menubar)
        QWidget.setTabOrder(self.tbRun, self.listCommands)
        QWidget.setTabOrder(self.listCommands, self.listBatch)
        QWidget.setTabOrder(self.listBatch, self.tbStop)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBatch.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuXYController.menuAction())
        self.menubar.addAction(self.menuLaser_Controller.menuAction())
        self.menubar.addAction(self.menuValveController.menuAction())
        self.menubar.addAction(self.menuPump_Reader.menuAction())
        self.menubar.addAction(self.menuMass_Spectrometer.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionExit)
        self.menuBatch.addAction(self.actionStartNewBatch)
        self.menuBatch.addSeparator()
        self.menuBatch.addAction(self.actionNCCViewer)
        self.menuXYController.addAction(self.actionXYOpenStatusPage)
        self.menuXYController.addAction(self.actionXYOpenLogPage)
        self.menuXYController.addAction(self.actionReboot_XY)
        self.menuXYController.addSeparator()
        self.menuXYController.addAction(self.actionManualControl)
        self.menuValveController.addAction(self.actionValveOpenStatusPage)
        self.menuValveController.addAction(self.actionValveOpenLogPage)
        self.menuValveController.addAction(self.actionReboot_Valve)
        self.menuHelp.addAction(self.actionViewPyMSLog)
        self.menuHelp.addAction(self.actionViewPyMSSettings)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAboutPyMS)
        self.menuPump_Reader.addAction(self.actionPumpOpenStatusPage)
        self.menuPump_Reader.addAction(self.actionPumpOpenLogPage)
        self.menuPump_Reader.addAction(self.actionReboot_Pump)
        self.menuMass_Spectrometer.addAction(self.actionStartMIDScan)
        self.menuMass_Spectrometer.addAction(self.actionStartProfileScan)
        self.menuMass_Spectrometer.addSeparator()
        self.menuMass_Spectrometer.addAction(self.actionStopScan)
        self.menuLaser_Controller.addAction(self.actionLaserOpenStatusPage)
        self.menuLaser_Controller.addAction(self.actionLaserOpenLogPage)
        self.menuLaser_Controller.addAction(self.actionReboot_Laser)
        self.menuLaser_Controller.addSeparator()
        self.menuLaser_Controller.addAction(self.actionCO2LaserOn)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"PyMS - Python Mass Spectrometry", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.actionStartNewBatch.setText(QCoreApplication.translate("MainWindow", u"Start New Batch", None))
#if QT_CONFIG(tooltip)
        self.actionStartNewBatch.setToolTip(QCoreApplication.translate("MainWindow", u"Create a new batch", None))
#endif // QT_CONFIG(tooltip)
        self.actionXYOpenStatusPage.setText(QCoreApplication.translate("MainWindow", u"Open Status Page", None))
        self.actionXYOpenLogPage.setText(QCoreApplication.translate("MainWindow", u"Open Log Page", None))
        self.actionValveOpenStatusPage.setText(QCoreApplication.translate("MainWindow", u"Open Status Page", None))
        self.actionValveOpenLogPage.setText(QCoreApplication.translate("MainWindow", u"Open Log Page", None))
        self.actionManualControl.setText(QCoreApplication.translate("MainWindow", u"Calibrate X-Y Stage", None))
        self.actionViewPyMSLog.setText(QCoreApplication.translate("MainWindow", u"View PyMS Log", None))
        self.actionAboutPyMS.setText(QCoreApplication.translate("MainWindow", u"About PyMS", None))
        self.actionViewPyMSSettings.setText(QCoreApplication.translate("MainWindow", u"View  / Edit PyMS Settings", None))
        self.actionPumpOpenStatusPage.setText(QCoreApplication.translate("MainWindow", u"Open Sataus Page", None))
#if QT_CONFIG(tooltip)
        self.actionPumpOpenStatusPage.setToolTip(QCoreApplication.translate("MainWindow", u"Open Status Page", None))
#endif // QT_CONFIG(tooltip)
        self.actionPumpOpenLogPage.setText(QCoreApplication.translate("MainWindow", u"Open Log Page", None))
        self.actionStartMIDScan.setText(QCoreApplication.translate("MainWindow", u"Start MID Scan", None))
        self.actionStartProfileScan.setText(QCoreApplication.translate("MainWindow", u"Start Profile Scan", None))
        self.actionStopScan.setText(QCoreApplication.translate("MainWindow", u"STOP Scan", None))
        self.actionLaserOpenStatusPage.setText(QCoreApplication.translate("MainWindow", u"Open Status Page", None))
        self.actionLaserOpenLogPage.setText(QCoreApplication.translate("MainWindow", u"Open Log Page", None))
        self.actionCO2LaserOn.setText(QCoreApplication.translate("MainWindow", u"Manual Laser Control", None))
        self.actionReboot_XY.setText(QCoreApplication.translate("MainWindow", u"Reboot X-Y Raspberry Pi", None))
        self.actionReboot_Laser.setText(QCoreApplication.translate("MainWindow", u"Reboot Laser Raspberry Pi", None))
        self.actionReboot_Valve.setText(QCoreApplication.translate("MainWindow", u"Reboot Valve Raspberry Pi", None))
        self.actionReboot_Pump.setText(QCoreApplication.translate("MainWindow", u"Reboot Pumps Raspberry Pi", None))
        self.actionNCCViewer.setText(QCoreApplication.translate("MainWindow", u"Ncc Viewer", None))
        self.actionHelp.setText(QCoreApplication.translate("MainWindow", u"Help", None))
        self.tbValve1.setText("")
        self.tbValve2.setText("")
        self.tbValve6.setText("")
        self.tbValve7.setText("")
        self.tbValve8.setText("")
        self.tbValve3.setText("")
        self.tbValve4.setText("")
        self.tbValve10.setText("")
        self.tbValve11.setText("")
        self.tbValve5.setText("")
        self.tbValve13.setText("")
        self.tbValve12.setText("")
        self.lblMS.setText(QCoreApplication.translate("MainWindow", u"Connecting . . .", None))
#if QT_CONFIG(tooltip)
        self.btnHidenMID.setToolTip(QCoreApplication.translate("MainWindow", u"Run a MID Scan", None))
#endif // QT_CONFIG(tooltip)
        self.btnHidenMID.setText("")
#if QT_CONFIG(tooltip)
        self.btnHidenProfile.setToolTip(QCoreApplication.translate("MainWindow", u"Run a Profile Scan", None))
#endif // QT_CONFIG(tooltip)
        self.btnHidenProfile.setText("")
#if QT_CONFIG(tooltip)
        self.btnHidenStop.setToolTip(QCoreApplication.translate("MainWindow", u"Stop Scanning", None))
#endif // QT_CONFIG(tooltip)
        self.btnHidenStop.setText("")
        self.lblLaserPower.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Elapsed Time", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Remaining Commands", None))
        self.lblStatus.setText(QCoreApplication.translate("MainWindow", u"Status: Manual Control", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Batch", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Location / Sample", None))
        self.tbStop.setText("")
        self.tbRun.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.lblIonPump.setText(QCoreApplication.translate("MainWindow", u"Ion Gauge", None))
        self.lblTurboPump.setText(QCoreApplication.translate("MainWindow", u"Turbo Gauge", None))
        self.lblTankPump.setText(QCoreApplication.translate("MainWindow", u"Tank Gauge", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Batch Items  (Currrent / Next)", None))
        self.linePlanchet.setText("")
        self.lineLocation.setText("")
        self.lineIonPump.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineTurboPump.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineScrollPump.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineXPosition.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lineYPosition.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"X Position", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Y Position", None))
        self.lblCurrent.setText(QCoreApplication.translate("MainWindow", u"Current Command", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Results", None))
        self.lblAalarm.setText("")
        self.lblFinishTime.setText("")
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Current Command", None))
        self.btnNCCViewer.setText(QCoreApplication.translate("MainWindow", u"NCC Viewer", None))
        ___qtablewidgetitem = self.tableResults.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Date", None));
        ___qtablewidgetitem1 = self.tableResults.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Data File", None));
        ___qtablewidgetitem2 = self.tableResults.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Sample", None));
        ___qtablewidgetitem3 = self.tableResults.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Best Fit", None));
        self.lineN2Pressure.setText(QCoreApplication.translate("MainWindow", u"0.0", None))
        self.lblN2Pump.setText(QCoreApplication.translate("MainWindow", u"N2 Gauge", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuBatch.setTitle(QCoreApplication.translate("MainWindow", u"Batch", None))
        self.menuXYController.setTitle(QCoreApplication.translate("MainWindow", u"X-Y Controller", None))
        self.menuValveController.setTitle(QCoreApplication.translate("MainWindow", u"Valve Controller", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u" | ", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Support", None))
        self.menuPump_Reader.setTitle(QCoreApplication.translate("MainWindow", u"Pump Reader", None))
        self.menuMass_Spectrometer.setTitle(QCoreApplication.translate("MainWindow", u"Hiden Mass Spectrometer", None))
        self.menuLaser_Controller.setTitle(QCoreApplication.translate("MainWindow", u"Laser Controller", None))
    # retranslateUi

